emberjs/website

source/guides/getting-started/show-only-incomplete-todos.md
the comment, as it was, implied (to me) that the code snippet was hiding existing code for brevity, but actually, there are no other child routes at this point.
=> change comment to match preceding step in tutorial

source/guides/templates/rendering-with-helpers.md
See github.com/emberjs/ember.js/issues/2242 and github.com/emberjs/ember.js/pull/3017
=> Leading underscore no longer a requirement

Rakefile
Ember Data's build tools were refactored recently and `npm run dist`
no longer works. This pr updates the generate_ember_data_docs script
to call `npm run build:production`
=> Fix Ember Data API docs build script

source/guides/cookbook/user_interface_and_interaction/using_modal_dialogs.md
Using `{{outlet modal}}` produces warning:
~~~~
DEPRECATION: Using {{outlet}} with an unquoted name is not supported. Please update to quoted usage '{{outlet "modal"}}'.
at outletHelper (http://localhost:4200/assets/vendor.js:34983:13)
at Object.__exports__.default.Ember.Handlebars.template.main (grruca/templates/application.js:10:105)
at ret (http://localhost:4200/assets/vendor.js:11023:32)
at CoreView.extend.render (http://localhost:4200/assets/vendor.js:56437:20)
at EmberRenderer_createElement [as createElement] (http://localhost:4200/assets/vendor.js:53540:16)
at EmberRenderer.Renderer_renderTree [as renderTree] (http://localhost:4200/assets/vendor.js:23631:24)
at EmberRenderer.scheduledRenderTree (http://localhost:4200/assets/vendor.js:23708:16)
at Queue.invoke …
=> Remove deprecated code example from Cookbook

source/blog/2013-08-29-ember-1-0-rc8.md
The word 'that' did not make sense in the sentence, I therefore removed it.
=> Remove a superfluous 'that'

source/blog/2015-01-08-inside-fastboot-faking-the-dom-in-node.md
The DOM Standard https://dom.spec.whatwg.org/ is maintained by the WHATWG, not the W3C.
=> Fix DOM spec organization

source/guides/testing/test-helpers.md, source/guides/testing/testing-components.md, source/guides/testing/testing-controllers.md, source/guides/testing/testing-models.md, source/guides/testing/testing-routes.md, source/guides/testing/testing-user-interaction.md, source/guides/testing/unit-testing-basics.md
Fixed the broken jsbins in the testing guide - they were referencing an older version of handlebars.
=> Fix broken jsbin examples in testing guide - Issue #1881

source/guides/testing/unit-test-helpers.md
Instead of relying on redirection from GitHub, this change links directly to the repo's current home.
=> Correct path to ember-qunit

source/guides/testing/testing-components.md
Sometimes those opening curly braces just need more space to breathe.
More importantly, this is more consistent with code elsewhere in the guides.
=> Add space before opening curly braces

source/guides/models/finding-records.md
Remove quotes from the query string in an example of a URL that’s requested with store.find.
https://github.com/emberjs/data/issues/2738
=> Edit sample code in finding-records.md

README.md
The incorrect opening fence for the code block is causing markdown to render README incorrectly.
=> Fix opening codeblock fence

Rakefile
This is nice when you only want to build/publish ember data docs.
Because Middleman will generate docs for ember with ember data,
this often leads to accidentally changing the ember docs when updating
ember data.
=> add Rake task to only generate Ember Data docs

source/blog/2014-09-13-core-team-meeting-minutes-2014-08-14.md
September 14th's core team meeting minutes appears with a September 1st date. This PR fixes that :dancer:
=> Fix Sep 14 blog post date

source/guides/cookbook/helpers_and_components/adding_google_analytics_tracking.md
This bit me on the bottom because I was adding a Universal Analytics tracking code to the Classic Analytics snippet in this article. My own fault for copying and pasting, but I thought it might be useful to be explicit to avoid further confusion for anyone else.
Classic: https://developers.google.com/analytics/devguides/collection/gajs/ (`ga.js`)
Universal Analytics: https://developers.google.com/analytics/devguides/collection/analyticsjs/ (`analytics.js`)
I'd be happy to update the code to the new Google UA snippet if anyone things its worth it.
=> Avoid confusion by making Classic version explicit

source/security/index.md
The RFPolicy link on the website is currently broken.
=> Fix broken rfpolicy link

source/guides/deprecations/index.md
Lifted from https://github.com/emberjs/website/pull/1951
I've extracted only the deprecation guide entry (with a slight tweak or two). I remain uncertain where the longer guide should live, or if the voicing/tense is correct etc. But we need this entry ASAP, so I'd like to decouple and just merge the uncontroversial part of this.
=> Deprecation guide for app initializers

source/blog/2015-03-24-ember-data-1-0-beta-16-1-released.md
=> Add a blog post announcing the release of Ember Data 1.0.0-beta.16.1

source/deprecations/v1.x.html.md
https://github.com/emberjs/ember.js/pull/10711 should be updated to link to this once published
=> Adds a guide on bound `style` warning

source/deprecations/v1.x.html.md
/cc @trek @wagenet @rwjblue @cibernox
This generally cleans up some 1.12 guides. Most significant, IMO is that I am changing the headlines to not repeat `Deprecate some foo` for each headline. Repeating a single word makes the text very hard to scan. This is just an example, though it is not the headlines I am changing:
vs
Just wanted to note it for the future, since once we write a headline it is painful to change it (the links from deprecation in old versions of Ember would break).
I'll follow up this PR with one to Ember ensuring the linking is correct.
=> Clean up 1.12 deprecations

source/deprecations/v1.x.html.md
Mention that `in` and `as` are deprecated in the context switching section.
=> Point to in and as deprecations from context-switching

source/community/meetups.html.erb, source/layout.erb
In response to https://github.com/emberjs/website/issues/2103 this commit moves the inclusion of the google maps libraries from layout.erb to meetups.html.erb
=> Only load google maps libraries on meetups page

source/deprecations/v1.x.html.md
Under ["More Consistent Handlebars Scope - Transition Plan"](http://emberjs.com/guides/deprecations#toc_transition-plan), there's no corresponding transition for using just `{{#each}}`:
```handlebars
<ul>
{{#each}}
<li>{{name}}</li>
{{/each}}
</ul>
```
For consistency, it would be better to also add sample code using the new syntax with `this` (or `controller`) as the context. For instance, when you're using an `ArrayController` and you want to proxy instead of calling `model` directly.
=> Add missing transition plan in handlebars scope deprecation

source/javascripts/app/builds/app.js
We were previously relying on the fact that `projectFilter` was a
string that happened to be the beginning part of the filenames. This
adds the specific value that we need.
Fixes #2108.
=> Fix build base file name.

source/blog/2015-03-27-ember-1-11-0-released.md
the 'either' word would be very helpful for me when I tested this feature, so I wanted to underline that this is an alternative and only 1 colorComponent is rendered.
=> Specify the component helper example in the Ember 1.11.0 blog

source/javascripts/app/builds/templates/_files_table.js.hbs, source/javascripts/app/builds/templates/_project_listing.js.hbs, source/javascripts/app/builds/templates/application.js.hbs, source/javascripts/app/builds/templates/components/copy-clipboard.js.hbs
RIP `bind-attr` 
Also updated to block params in each helpers
@rwjblue I don't really like the empty string for the truth case.
```js
<div class="left {{if project.beta1Completed '' 'future-image'}}">
```
But this is not any better.
```js 
<div class="left {{unless project.beta1Completed 'future-image'}}">
```
Where is `beta1Completed` coming from?
Cheers
=> [FEATURE] removing bind-attr from the build ember app

source/deprecations/v1.x.html.md
To match recent changes in Ember.
=> Add legacy anchors to deprecations

source/deprecations/v1.x.html.md
Added description of how to use the itemController when you switch from "in" syntax to "as" syntax for {{each}}.
=> Add "itemController" description for {{each}}

source/javascripts/app/builds/app.js
Credit goes to @knownasilya for pointing it out and @fivetanley for uploading the missing files to s3.
=> Add Ember Data beta 16.1 release to the builds page.

source/blog/2015-02-07-ember-1-10-0-released.md
The block params introduction example incorrectly uses `name` in the template instead of `fullName`.
http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_block-params
=> Corrected incorrect yielded block param in example

source/stylesheets/blog.css.scss
This is just a small tweak for the blog titles on actual blog post pages. The [IE8 Support Update](http://emberjs.com/blog/2015/04/20/ie8-support-update.html) post, in particular.
Here's the before:
And with this commit:
=> Fix blog title formatting when the line wraps.

source/stylesheets/blog.css.scss
This fixes a regression on single line post titles caused by #2146
=> Fix ribbon on blog post titles that don't wrap.

Rakefile
Running `bundle exec rake generate_docs` with a fresh clone of the Ember.js repository fails because the package `ember-cli-yuidoc` is not installed.
````
$ bundle exec rake generate_docs
Generating docs data from /home/yoran/Projects/emberjs/ember.js... npm run docs
> ember@1.13.0-beta.1 docs /home/yoran/Projects/emberjs/ember.js
> ember yuidoc
version: 0.2.3
The specified command yuidoc is invalid. For available options, see `ember help`.
````
Solved by running `npm install` before generating the docs.
=> Run 'npm install' before generating the documentation for Ember.js

source/blog/2015-05-13-ember-1-12-released.md
`export default` should only be used once, the example uses it twice. I tried that and an an error.
=> Ember 1.12 blog post, fix instance initializers example

source/documentation.md, source/layouts/guide.erb
If you go to `http://emberjs.com/guides` manually, it will take you to v1.10.0 of the guides. This changes that to go to `http://guides.emberjs.com/`, which redirects to the latest version.
If there was a path, it'll still take you to v10 so old links don't stop working.
=> Redirect to latest guides instead of specific

source/deprecations/v1.x.html.md
Related to https://github.com/emberjs/ember.js/pull/11387
This does not include a deprecation section for migrating off `viewName` or `{{view "select"}}`, both of which will warrant their own sections.
=> Deprecation Guide for Ember.View

source/deprecations/v1.x.html.md
`{{view}}` and `{{controller}}` are deprecated.
=> Deprecated keywords

source/deprecations/v1.x.html.md
A short explanation of why `Ember.Select` is deprecated and notes on how modern Ember provides features that allow one to create the functionality of `Select` without the problematic aspects of `Ember.Select`. Links to a [jsbin showing a `my-select` component](http://jsbin.com/fotuqa/edit?js,output), a jsbin demonstrating usage of select without a component (but with Improved Actions) and [links to Ember Observer's category page for "select"](http://emberobserver.com/categories/select) and [the emberx-select addon](http://emberobserver.com/addons/emberx-select)) as migration suggestions.
cc @mixonic
=> Adds a deprecation guide section about Ember.Select

source/deprecations/v1.x.html.md
The last paragraph is actually not true until https://github.com/emberjs/ember.js/pull/10582 gets merged
=> Note on array/reduce computed being deprecated

source/blog/2015-06-12-ember-1-13-0-released.md
- Spelling
- Clarify that `{{link-to}}` remains
- Fewer bold
*Feel free to include all, some or none of these as you see fit.*
=> Minor updates to blogpost

source/blog/2015-06-12-ember-1-13-0-released.md
The block helper should be beginning with `#`.
=> Fix example code in `2015-06-12-ember-1-13-0-released.md`

source/javascripts/app/builds/templates/_project_listing.js.hbs, source/javascripts/app/builds/templates/index.js.hbs, source/stylesheets/builds.css.scss, source/stylesheets/site.css.scss
The deprecations guide is chock-full of useful information for those working with builds other than stable. Let's reference it on that page.
Also includes some CSS cleanup in the "builds" application. Looked like there were some leftovers.
=> Add more explicit referencing of deprecations guide

source/blog/2015-06-18-ember-data-1-13-released.md
JSON API spec requires this to be called `detail` not `details`, c.f http://jsonapi.org/format/#error-objects
=> Fix typo in ED release announcement

source/blog/2015-06-18-ember-data-1-13-released.md
status is a number
Both according to docs http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_handleResponse and to own experience :)
=> Fix another typo in ED release announcement

source/deprecations/v1.x.html.md
Following discussion here: https://github.com/emberjs/ember.js/pull/11671
/cc @mixonic
=> Move beforeObserver deprecation entry from 1.10 to 1.13

source/javascripts/app/builds/app.js
In the tagged releases page there are 15 total ember and ember-data files that I believe can be removed.
1. removes /tags//ember.min.js (a year ago)
- removes /tags//ember.prod.js (a year ago)
- removes /tags//ember-template-compile.js (a year ago)
- removes /tags//ember.js (a year ago)
- removes tags/_ribbon/ember-data.min.js (22 days ago)
- removes tags/_ribbon/ember-data.prod.js (22 days ago)
- removes tags/_ribbon/ember-data.js.map (22 days ago)
- removes tags/_ribbon/ember-data.js (22 days ago)
- removes tags/1.13.0/ember-data.prod.js (a month ago)
- removes tags/1.13.0/ember-data.js.map (a month ago)
- removes tags/1.13.0/ember-data.js (a month ago)
- removes tags/1.13.0/ember-data-min.js (a month ago)
- removes tags/1.0.0-beta.6/ember-data.prod.js (a year ago)
- removes …
=> Remove 15 non version files from tagged releases on builds page

source/deprecations/v1.x.html.md
Again, i'm not a great writer, but at least there is some documentation.
See emberjs/ember.js#11767
=> Add deprecation guide for Controller#needs

source/guidelines.html.erb
I found the duplication in the diversity statement to have the effect of sounding a little too informal.  I think this makes it sound a little cleaner and more serious.
Since the line is long, the changes are:
etc ~~etc etc~~
~~and so on and so forth~~
=> reduce duplication in the diversity statement

source/stylesheets/site.css.scss
Fixes #2263 
Style changes only.
[Browser Support](http://caniuse.com/#feat=multicolumn)
This should work in all major browsers. In <= IE9 I believe this will fall back to a single column twice as tall. I think the increase in comprehensibility for everyone else is worth the tradeoff.
Before:
After:
=> Change method/property/event ordering from linewise to columnwise

source/stylesheets/api.css.scss
Improves the readability of the API docs by removing the uppercase text transform. See #2276
=> No uppercase text transform for API headers

source/blog/2015-06-18-ember-data-1-13-released.md
Fixing links to http://jsonapi.org/format/, self referencing links formatted like this: [http://jsonapi.org/format/#document-resource-objects]() we're resolving to http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html
=> Fixing links in 2015-06-18-ember-data-1-13-released.md

source/javascripts/app/api/api.js
In response to #2264: Now we're going through each of the pane's api-option inputs and confirming that they're toggled appropriately on each change. This appears to fix the issue of "Show inherited, show private, unshow inherited, wait why's that still there, oh god make them go away."
Hope this helps!
=> Fix unexpected toggling of displayed items in the API panes.

source/deprecations/v1.x.html.md
- Adds links out to MDN for more information.
- Apologies for the uninventive examples.
See #2256
=> Deprecation guide for `Ember.create` and `Ember.keys`

source/deprecations/v1.x.html.md
Adds missing deprecation description for Ember 1.13.5 - Deprecate reverse argument ordering in ```Ember.observer```.
See #2256 for checklist of all missing deprecations.
=> Add deprecation for reversed observer arguments

source/deprecations/v1.x.html.md, source/guides/deprecations/1.11/instance-initializers.md
Adds a deprecation guide for the deprecations introduced by instance initializers. Should be merged with emberjs/ember.js#10256.
=> Instance initializers deprecation

source/deprecations/v1.x.html.md
=> Deprecation guide for `Ember.oneWay`.

source/blog/2015-08-16-ember-2-1-beta-released.md
Draft of the 2.1 beta blog post. [Rendered](https://github.com/mixonic/website/blob/blog-2.1/source/blog/2015-08-16-ember-2-1-beta-released.md)
=> 2.1 beta blog post

source/deprecations/v1.x.html.md
We were slightly burned by this when removing all legacy usage of `{{bind-attr}}` and @locks suggested I open this pull.
=> Added deprecation warning about using class bound dasherized values

source/deprecations/v1.x.html.md
My first commit towards fixing #2256.
=> Added deprecation guide about Ember.computed.any

source/deprecations/v1.x.html.md
See #2256 
Fixes:
> Options to the {{#each helper that trigger a legacy and poorly performing legacy layer. These options 
> are: itemView, itemViewClass, tagName, emptyView and emptyViewClass
=> Add deprecation guide for all the each helper options

Rakefile
Create rake task to just generate the ember side of the docs.
(There's already one for just the ember-data side.)
This is helpful if you're testing doc changes to only one side of the project.
=> Expose rake task to generate just the ember docs (not data)

source/deprecations/v1.x.html.md
`Object.keys` only takes a single parameter, but the example was passing multiple objects for some reason, rather than a single hash with multiple attributes.
=> Fix Ember.keys Deprecation Example

data/meetups.yml
This PR updates 2 things for the Ember Columbus meetup:
1. Removes Ricky Gilbert from the organizer list as he is moving away
2. Updates the URL to use the Meetup URL (which hopefully will improve crawling by aggregators like Ember Weekly)
=> Update Columbus meetup

source/blog/2015-06-18-ember-data-1-13-released.md
This updates the `findRecord` examples to be more representative of realistic usage in a route's model hook.
=> Update model hook snippets for new finders

source/blog/2015-10-04-ember-2-1-released.md
Adds a blog post for Ember 2.1 and 2.2 beta. I'll be out of pocket until Sunday afternoon, the following need to happen before this could go live:
=> Ember 2.1 blog post

source/deprecations/v2.x.html.md
As requested by @rwjblue in [comment](https://github.com/emberjs/ember.js/pull/12370#issuecomment-145419368) in [pull request](https://github.com/emberjs/ember.js/pull/12370) which added deprecations.
=> Add info about deprecated function as second argument in deprecate/warn/assert

source/deprecations/v1.x.html.md
=> Add guide for Ember.immediateObserver deprecation

source/about.html.erb
The last time the G+ page was updated was in 2013.  Seems best to remove it ;-)
=> Remove G+ link from home page

Gemfile, Gemfile.lock
The following warning is shown since bundler 1.7.
```
Warning: this Gemfile contains multiple primary sources. Using `source`
more than once without a block is a security risk, and may result in
installing unexpected gems. To resolve this warning, use a block to
indicate which gems should come from the secondary source. To upgrade
this warning to an error, run `bundle config disable_multisource true`.
```
See detail: https://github.com/bundler/bundler/blob/master/CHANGELOG.md#170-2014-08-13
=> Stop using multiple `source` in primary

source/blog/2015-05-13-ember-1-12-released.md
Setters expect the value to be returned, see [docs](http://emberjs.com/api/classes/Ember.ComputedProperty.html#method_set).
I got bit by this and wasted about half a day trying to figure out why property changes weren't being fired.
=> add return value for setter

source/blog/2015-11-16-ember-2-2-released.md
Contextual components example is missing a `#` on the opening component tag.
=> fix typo in 2.2 blog post

source/blog/2015-11-17-ember-data-2-2-released.md
Was pointing to the Ember.js changelog, not the ED changelog as expected.
=> Fix 2.3-beta.1 changelog link in 2.2 release blog post

source/deprecations/v1.x.html.md
working through issue https://github.com/emberjs/website/issues/2256
These are the remaining 1.13.7 deprecations
=> Add 1.13.7 Deprecations to deprecation guide

data/meetups.yml
We're changing the location of our Columbus meetup to be more centrally located downtown, so this updates the Meetups map to reflect that change.
=> Update Ember Columbus meetup location

data/users.yml
I noticed that most logos on the Ember users list are submitted with the exact display dimensions of 210x103 (as recommended in the instructions). With the growing popularity of high-resolution displays, it may be beneficial to recommend that these logos be uploaded at a higher resolution (420x206). They will still be displayed at 210x103, but with a sharper appearance on retina-quality displays.
I noticed that the Acorns logo is already doing this: https://github.com/emberjs/website/pull/2390
I have submitted the Test Double logo to do this as well: https://github.com/emberjs/website/pull/2439
=> Add instructions for high-resolution Ember user logos

source/community.html.erb
Add Ember Twiddle option to places you can host a failing or a reduced test case.
=> Add Ember Twiddle option

source/blog/2016-01-14-security-releases-ember-1-11-4-1-12-2-1-13-12-2-0-3-2-1-2-2-2-1.md
This is the blog post announcing the patched Ember releases that contain a fix for CVE-2015-7565. This PR can be merged once we verify:
1. `master`, `stable` and `beta` branches have been patched
2. The corresponding releases have had their tags pushed to GitHub (the Compare links won't work until then)
@rwjblue
=> Blog post for CVE-2015-7565

data/meetups.yml
This meetup slowed down and finally became
inactive. I wrote a blog post about the reasons
but in summary: our island is too small for a 
framework/language specific meetup.
We started a new meetup aimed at the general
developer community an it seems to be doing a lot
better. There's a lot of interest about Ember.js
so we'll keep doing talks and hand on learning
events.
=> Remove the San Juan, PR meetup

source/javascripts/app/examples/loading/app.js
Currently, the example grabs all of Ember's PRs over the network then splices out all but the 3 most current. GitHub's API has pagination, so this isn't necessary and just increases network load.
=> Use GitHub Pagination for the loading example

data/meetups.yml
If American cities show their states, Canadian cities might as well show their provinces.
I also threw in a fix for [the broken Silicon Valley link](https://github.com/emberjs/website/issues/2470).
=> Give Canadian meetups province-level information

data/meetups.yml
The missing lat / long data was causing the link on http://emberjs.com/community/meetups/ to go directly to the meetup's page instead of interacting with the google map (like the other links do). 
I pulled the lat/long from the address they typically host their startup from as seen on: http://www.meetup.com/Ember-Riverside-Meetup/events/224108684/, or directly on the image http://photos1.meetupstatic.com/photos/event/9/d/8/2/600_371440322.jpeg
I also fixed the url for the organizer's profile image.
=> Add missing lat long for meetup in Riverside, CA

source/deprecations/v1.x.html.md
Documentation isn't my strong suit, happy to make any changes.
Also, I added this deprecation immediately after Ember.ArrayController because they are some what related and it seemed like they should be next to each other.
=> Added deprecation for `Ember.SortableMixin`

data/meetups.yml
I was reviewing the list of meetups on http://emberjs.com/community/meetups/ and noticed a couple that appear to no longer be active.
- Kyiv, Ukraine (http://ember-club.kiev.ua/)
- Ottawa, ON (http://www.meetup.com/Ember-js-Ottawa/)
I've opened up this PR which just removes them from the list. I didn't know if there was additional follow up that might need to happen with these meetups? 
I'm happy to modify PR or try to contact these groups if it's helpful!
=> Remove missing meetups

source/blog/2016-02-29-ember-2-4-released.md
[Rendered](https://github.com/mixonic/website/blob/blog-2.4/source/blog/2016-02-29-ember-2-4-released.md)
@rwjblue please keep an eye out in case I missed something regarding deprecations. I don't think we landed any of the ones we've been discussing ([`Ember.ArrayProxy`](https://github.com/emberjs/ember.js/pull/12843) for example).
=> Ember 2.4 blog post

source/blog/2016-02-29-ember-2-4-released.md
Fixes a typo in `Ember.assign` example.
=> Fix typo in Ember 2.4.0 release post

data/meetups.yml
We changed our Meetup name some time ago, so I was surprised that the Ember Community page still listed the old link. Although it redirects to the proper/new Meetup page, I think it needs to be corrected for Ember Weekly to pull our dates. I also updated our organizers while I was at it, and refined the lat/lng coordinates to our common meetup location.
Here is my member page if you need verification (technically not an organizer but a loyal attendee): http://www.meetup.com/EmberMN/members/124187072/
=> Update Minneapolis / St. Paul Meetup Listing

source/layouts/guide.erb
Fixes https://github.com/emberjs/guides/issues/1302.
Guides version was hardcoded into the path.
I have added logic to fetch the latest version from the guides'
versions.json.
=> Fixes https://github.com/emberjs/guides/issues/1302

source/javascripts/app/builds/app.js
Per bowers documentation `--dev` is not an install option: http://bower.io/docs/api/#install
=> Using proper options with bower install

source/_survey-reminder.html.erb, source/ember-community-survey-2016.html.erb, source/layout.erb, source/stylesheets/_survey-reminder.scss, source/stylesheets/site.css.scss
This adds a simple reminder bar to the website to remind folks to fill out their 2016 survey. Preview below.
@mixonic can you give me some direction on the copy? Also, should I use a hard date as the stopping point or a little Javascript for something like "2 days left"?
Preview:
Mobile (responsive page): 
Mobile (unresponsive page):
=> Add survey reminder to layout — WIP

source/deprecations/v1.x.html.md
I've spent quite some time debugging this (see [my blog post](http://balinterdi.com/2016/02/03/binding-style-attributes-warning-in-ember.html)), and although the section in the guides is correct, I think others would benefit by having this emphasized.
=> Emphasize style attribute binding should not be quoted

source/blog/2016-03-13-ember-data-2-4-released.md
The embedded records mixin is located at `'ember-data/serializers/embedded-records-mixin'` not `'ember-data/mixins/embedded-records'` as I found out when copy/pasting the example. This fixes the example code and adds a reference to the pull request that introduced the changes.
=> Fix EmbeddedRecordsMixin import path

lib/api_docs.rb, source/layouts/api.erb
=> Hide private and deprecated classes and namespaces from sidebar.

source/community.html.erb
Moves the community sections around according to priority.  Specific instructions came from this issue: https://github.com/emberjs/website/issues/2520
> Flip the the Stuck? Lost? header (and content) to be immediately beneath the meetup video
>  move the "in a giving mood?" section down to where the Stuck? Lost? section was
=> Move some community page sections, according to priority

source/deprecations/v2.x.html.md
Adding documentation for planned deprecation of Ember.Handlebars.SafeString as discussed in this issue: https://github.com/emberjs/ember.js/issues/13191
=> Add deprecation docs for Ember.Handlebars.SafeString

source/deprecations/v2.x.html.md
this adds the documentation for the deprecation of didInitAttrs.
=> add documentation for didinitattrs deprecation

source/ember-community-survey-2016.html.erb
The vertical axis on the first graph "How long have you been working with Ember?" is labeled "Months", but it seems that it should be "Percent".
=> Fix survey graph label

data/team.yml
As announced at EmberConf 2016, I'm alumnizing myself from the Ember.js core team to focus on my  semi-professional career as a hand model.
=> Alumnize Trek

source/deprecations/v2.x.html.md
Documents [this PR](https://github.com/emberjs/ember.js/pull/13268) originating from [this issue](https://github.com/emberjs/ember.js/issues/13183). I presume this change will be in 2.5.x so I documented it as such. I can obviously change this though.
=> Documentation for deprecation of model param in `{{render` helper

source/deprecations/v2.x.html.md
=> Add `{{#render` block deprecation.

source/blog/2016-04-11-ember-2-5-released.md
[Rendered](https://github.com/mixonic/website/blob/2.5-blog/source/blog/2016-04-11-ember-2-5-released.md)
Blockers:
=> Ember 2.5 blog post

source/deprecations/v2.x.html.md
Added `id` and `until` to each item just below the header. Not listed in the original issue, but I also added `id` and `until` to Ember.Backburner under 2.7
Issue https://github.com/emberjs/website/issues/2543
=> Add `id` and `until` information to 2.x deprecation guide items

source/deprecations/v2.x.html.md
From emberjs/ember.js#13016. Put it under ~~the 2.7 deprecations because I was unsure when this would actually be active~~ a new section for pending features.
=> Add  to deprecation guide

source/deprecations/v2.x.html.md
Per emberjs/ember.js#13344 it is being undeprecated.
EDIT: Do not merge just yet. We should wait at least until Ember 2.5.1 has shipped with the deprecation removed.
=> [On Hold] Removed `Ember.merge` from the list of 2.x deprecations. 

source/about.html.erb, source/stylesheets/about.css.scss
=> Improves the call to action in the frontpage

source/ember-users.html.erb, source/sponsors.html.erb, source/stylesheets/components/sponsors.css.scss, source/stylesheets/site.css.scss
Helping at the Denver Ember Meet-up Open Source Night.
I updated the emberjs.com/ember-users page to add responsive styling, this page utilizes the showcase component for displaying user logos. The update involved adding some new css rules, and I updated the markup for the showcase component from a table-based layout to a unordered list, which is a more appropriate and semantic markup structure for this content. 
The Showcase component is also used on the emberjs.com/sponsors page (which was already responsive) so I updated the markup structure there too, and made a few necessary CSS changes related to the sponsors page. I ended up moving some showcase-related styles from the sponsors scss partial to the main site scss partial so that all the showcase styles are co-located.
The Showcase …
=> new responsive styles and markup for Showcase component (ember-users and sponsors)

config.rb, source/blog/_sidebar.html.erb, source/blog/index.html.erb, source/stylesheets/blog.css.scss
Added pagination to blog pages and made it responsive ! please close this #2594 duplicate Pull request
=> responsive blog with pagination

source/community/meetups.html.erb
The map on the meetups page (http://emberjs.com/community/meetups/) is broken because the linked markerclusterer script returns a 404. The google code repo is shut down, in favor of github. This PR fixes the URL.
=> Fix broken meetups map

source/deprecations/v2.x.html.md
This feature is not deprecated in 2.6. It has been deferred until we have a proper RFC for safe strings.
=> Move safe string deprecation to 'future' section

source/deprecations/v2.x.html.md
This makes mention of `Ember.String.isHtmlSafe` and the related polyfill.
=> Updated the deprecation for `ember-htmlbars.ember-handlebars-safestring`

source/javascripts/app/builds/templates/index.js.hbs
Link to quick start guide is no longer hard coded.
Fixes https://github.com/emberjs/website/issues/2628
=> Used release version from model to construct quick start guide.

source/javascripts/app/builds/app.js, source/javascripts/app/builds/templates/index.js.hbs
Quick start guide was linking to versions that do not exist such as 2.6.1.  Now will only create links for latest MINOR versions such as 2.6.0.
=> Bug fix for quick start guide link on builds page

Gemfile, Gemfile.lock, source/stylesheets/builds.css.scss, source/stylesheets/examples.css.scss, source/stylesheets/guides.css.scss, source/stylesheets/highlight.css.scss, source/stylesheets/shared.css.scss, source/stylesheets/site.css.scss, source/stylesheets/survey.css.scss
This PR aims to transition the website's codebase to match the [guides repo](https://github.com/emberjs/guides).
- There were some incompatibilities between Compass & Bourbon. Compass is now `@import`ed feature-by-feature to ensure there are no name collision with Bourbon.
- Since browser support has gotten better, a few things like `text-shadow`, `background-clip` are now simply CSS properties, replacing Compass mixins.
=> Add Bourbon

source/stylesheets/site.css.scss
It's only a little thing on the [users](http://emberjs.com/ember-users/) page, but smaller logos should be center aligned to match the layout of the rest of the page:
**Before:**
**After:**
=> Fix minor display bug for users page

source/deprecations/v2.x.html.md
Deprecation guide update related to emberjs/ember.js#13553
[rendered](https://github.com/bmeurant/website/blob/master/source/deprecations/v2.x.html.md#enumerablecontains)
=> Add Enumerable.contains to deprecation guide

source/deprecations/v2.x.html.md
It's changing from `isHtmlSafe` to `isHTMLSafe`. See discussion here: https://github.com/emberjs/ember.js/pull/13666#issuecomment-233029252.
=> Updated the deprecation for `ember-htmlbars.ember-handlebars-safestring`.

source/stylesheets/base/_variables.scss
@rwjblue one addon to my last PR...
Found that commenting the red highlight made the search hits real light. Just adding back highlight-red fixed it:
Before:
After:
=> a little more surgical with the highlight bandaid bc search highlighting

source/stylesheets/components/legal.css.scss, source/stylesheets/components/logos.css.scss, source/stylesheets/components/security.css.scss, source/stylesheets/components/sponsors.css.scss
In the midst of the redesign it seems that the container sizes for the page content and header/footer has become inconsistent.
The header footer (and most of the site) uses a 960px container with `1rem` of horizontal padding.
However there are a few text containers (most noticeably the `.legal-wrapper`) which are MUCH smaller.
This is because the `.legal-wrapper` relied on `em` units.
Since the base `font-size` of these areas were reduced to `14px` then `60em` is no longer the loved `960px` but instead comes out to `840px`.
On top of this, the padding of the `.legal-wrapper` container also used `3rem` left and right.
This meant that the container was even smaller than the `840px`.
The content width of the navbar vs `.legal-wrapper` is `928px` to `756px` after padding and everything is …
=> Updates consistent container sizes

source/stylesheets/_header.scss
Browser version - Safari Version 8.0 (10600.1.25)
Before - 
After -
=> Added 'display: -webkit-flex' to support safari browsers < 9

source/javascripts/app/builds/templates/_files_table.js.hbs
This button encourages hotlinking. This is considered a bad practice.
Fixes emberjs/ember.js#14131
=> [BUGFIX] Remove Script Tag link

source/deprecations/v2.x.html.md
Per [blog post](http://emberjs.com/blog/2016/07/25/ember-2-7-and-2-8-beta-released.html#toc_code-enumerable-includes-code-and-code-array-includes-code) and this commit [84b16eb](https://github.com/emberjs/ember.js/commit/84b16eb36772b5292e392309d79ce66b0a70b1ab) (which is in beta), `Enumerable#contains` has been deprecated in Ember 2.8.
Figured I'd move the deprecation message into the appropriate section.
=> Moved the `Enumerable#contains` deprecation to the Ember 2.8 section

source/deprecations/v2.x.html.md
It is helpful to have this information in the deprecation guide.
=> Add link to Enumerable.includes polyfill.

source/community.html.erb, source/stylesheets/site.css.scss
This PR updates the community page (http://emberjs.com/community) to a responsive layout. 
The youtube embed is responsive, you may notice thin black bars at top/bottom of the youtube video at some smaller screen widths, its pretty minor and I'm not sure much can be done about it.
=> responsive Community page

source/stylesheets/site.css.scss, source/team.html.erb
This PR updates the Team page to a responsive layout. HTML was updated from `table`-based layout to `ul > li` structure. 
The team grid goes from 2-up to 3-up to 4-up.
=> responsive team page

README.md
Pretty self-explanatory, but this might save a small chunk of time for a lot of devs who don't have `bundle` set up on a machine yet and don't happen to use `gem` very often.
=> Document bundle install command

source/community.html.erb
I was trying to sign in to the Slack team from a new machine recently, and it took me a while to find our actual domain name (`embercommunity.slack.com`). The first place I looked was on the Community page, but I only found a link to the invite app. 
I figured linking "Ember Community Slack" to the team page itself will help a lot of folks who are on a similar search in the future.
=> Add link to Ember Community Slack

data/tomsters.yml, source/javascripts/tomster.js, source/stylesheets/site.css.scss, source/tomster.html.erb
This popped up this evening when I was showing my daughter all the different Zoeys and I thought "man it'd be nice to be able to see just the Zoeys".
Let there be filtering!
Caveat: I know **nothing** about Ruby/Middleman and figured this out mostly by Googling so I likely did some ignorant things. Please point these things out so I can make them mo betta!
=> Tomster filter

source/deprecations/v1.x.html.md
#escapeCSS is not natively implemented by Ember. Closes #14518.
=> Clarify escapeCSS use.

source/javascripts/app/examples/binding/templates/application.hbs
Current website looks like (6 != 7) 👎 :
But if we fix the indentation, it looks like (7 == 7) :+1: :
=> Add indentation to fix line numbers on homepage example

source/deprecations/v2.x.html.md
Deprecation for emberjs/ember.js#14482.
=> Add deprecation guide for renderToElement

source/deprecations/v2.x.html.md
This adds the deprecation guide for emberjs/ember.js#14441.
This guide could be expanded and reworded with some feedbacks. 
@ErikCH has shown interest in taking this documentation, but I wanted to get at least a basic documentation for this deprecation. Anyone else with more experience writing deprecations and using the `{{render` helper is welcome to take this further.
=> Add deprecation guide for {{render helper

source/deprecations/v2.x.html.md
It seems that the deprecation example was wrong. This updates it as per @chancancode's comment on https://github.com/emberjs/website/pull/2702#issuecomment-263493004.
Let me know if the change does make sense. Also should we mention that the `appendTo` can also receive an string with the selector?
=> Fix deprecation example of renderToElement

source/blog/2016-11-30-ember-2-10-released.md
[Rendered](https://github.com/emberjs/website/blob/ember-2-10-release/source/blog/2016-11-28-ember-2-10-released.md). Ship approvals (once nominated as complete and we remove the WIP):
---
=> Ember 2.10 unified blog post

config.rb
The changes introduced in #2731 broke direct `/builds` navigation.
=> [BUGFIX] Fixes `/builds` navigation

lib/versions.rb
Hey there :wave: 
In its current state the versions helper gives v2.9.0 as the current version, causing the quick start link on the homepage to link to the quick start guide for that version instead of v2.10.0.
This is because [this list](https://raw.githubusercontent.com/emberjs/guides.emberjs.com/master/snapshots/versions.json) that the versions are read from is not in order. I fixed this by sorting the list of versions using the Gem class.
=> Fix linking to incorrect version of quick start guide

source/deprecations/ember-data/v2.x.html.md, source/deprecations/index.html.md
This adds a new page to start building the ember-data 2.x deprecation guide along with the first deprecation guide.
I'm planning to put up an issue to track all of the deprecations in ember-data 2.x so we can hopefully get help covering the rest of the deprecations from the community. Having this first example up will make it easier for people to start helping out.
=> Add ember-data deprecation guide

source/deprecations/ember-data/v2.x.html.md
Adds `Ember.Date.parse` to the Ember Data deprecation guide.
Related to https://github.com/emberjs/data/issues/4695
=> Add deprecation guide for Ember.Date.parse

source/deprecations/ember-data/v2.x.html.md
Related to https://github.com/emberjs/website/pull/2745
This breaks up the single deprecation into one for `Ember.Date.parse`
and another for the `Date.parse` prototype extension.
Previously these deprecations were both part of the same guide but I
realized that they were actually two separate deprecations with their
own deprecation ids.
=> Fix ember data Date.parse deprecation guides

source/deprecations/ember-data/v2.x.html.md
As part of https://github.com/emberjs/data/issues/4695
=> Add deprecation guide to RESTSerializer.normalizeHash

source/deprecations/ember-data/v2.x.html.md
As part of https://github.com/emberjs/data/issues/4695.
=> Add guide to ember-data deprecations for version 2.11

source/deprecations/ember-data/v2.x.html.md
Adds guides for the deprecations introduced by the [`ds-overhaul-references` feature](https://github.com/emberjs/data/pull/4398/files).
=> Add deprecation guide for ds-overhaul-references

source/deprecations/ember-data/v2.x.html.md
Adds guide for removing `ds.serializer.private-should-serialize-has-many` deprecation to the Ember Data Deprecation guide
=> Add deprecation guide for JSONSerializer._shouldSerializeHasMany

source/deprecations/ember-data/v2.x.html.md
Adds a guide for `ds.rest-serializer.deprecated-key-for-polymorphic-type` to the Ember Data Deprecation Guide
=> Add deprecation guide for RESTSerializer.keyForPolymorphicType

source/deprecations/ember-data/v2.x.html.md
This adds the `ds.serializer.rest.queryRecord-array-response` deprecation to the deprecation guide for ember data.
=> Add deprecation guide for queryRecord array responses

source/deprecations/ember-data/v2.x.html.md
Adds guide for `ds.store.serialize` deprecation to the Ember Data Deprecation Guide.
=> Add deprecation guide for DS.Store.serialize

source/_header.html.erb
- Twin issue: https://github.com/emberjs/guides/pull/1753
The logo already navigates the user to the home page.
=> Remove About from main navigation

source/deprecations/ember-data/v2.x.html.md
Adds deprecation guides to the Ember Data Deprecation Guide for `JSONAPISerializer.payloadKeyFromModelName` and `JSONAPISerializer.modelNameFromPayloadKey`.
Deprecation ids included:
- `ds.json-api-serializer.deprecated-model-name-for-resource`
- `ds.json-api-serializer.deprecated-model-name-for-relationship`
- `ds.json-api-serializer.deprecated-payload-type-for-model`
- `ds.json-api-serializer.deprecated-payload-type-for-belongs-to`
- `ds.json-api-serializer.deprecated-payload-type-for-has-many`
=> Add deprecation guide for ds-payload-type-hooks features

source/deprecations/v2.x.html.md
deprecate Ember.K according to https://github.com/emberjs/ember.js/issues/14746
[rendered view](https://github.com/givanse/website/blob/0053f6e7f5d4556937e0b20dd5ca491c306f90cb/source/deprecations/v2.x.html.md#deprecations-added-in-212)
=> deprecate Ember.K

source/deprecations/ember-data/v2.x.html.md
Closes https://github.com/emberjs/website/issues/2780
@locks
=> Add deprecation guide for ds.deprecated-initializers #2780

source/javascripts/app/docsearch.js.erb, source/stylesheets/vendor/_docsearch.scss
Issue #2716 
- Updated algolia by modifiying CDN namespace version in order
to display an error message when no results found.
- Updated _docsearch.scss vendors accordingly to algolia CDN update
due to some markup update from Algolia.
Now when there is no result we have a UI feedback
=> Update algolia version

source/deprecations/v2.x.html.md
Please double check that this deprecation is under the right heading (added in 2.12).
Comments welcome!
[RFC](https://github.com/emberjs/rfcs/blob/master/text/0150-factory-for.md#example-deprecation-guide-migrating-from-_lookupfactory-to-factoryfor)
[Issue](https://github.com/emberjs/website/issues/2796)
=> add deprecation guide for migrating from _lookupFactory to factoryFor

source/deprecations/v2.x.html.md
This PR adds information related to the rename of `EmberRouter.router` to `EmberRouter.routerMicrolib` and the associated deprecation.
**Related PRs**: 
https://github.com/emberjs/ember.js/pull/14919
**Reviewers**
@rwjblue @locks 
**Changes**:
- Added information and examples for guidance on the rename
=> Adding deprecation information for the rename of Ember.Router.router

source/deprecations/v2.x.html.md
This PR quickly follows the already merged https://github.com/emberjs/website/pull/2806. 
**Reviewers**:
@rwjblue @krisselden 
**Changes**:
- Renaming references to `routerMicrolib` to `_routerMicrolib` to imply a private member.
=> Updating docs based on rename of routerMicrolib to _routerMicrolib

source/deprecations/v2.x.html.md
I wasn't sure if it would be appropriate or not to mention an addon that provides an alternate means of gaining back deprecated functionality. I wasn't trying to plug my addon. The only reason I opened this PR was because the addon was inspired by RFC discussions.
My feelings won't be hurt if this isn't merged 😄
=> Added notation about `ember-diff-attrs` to deprecation page

source/deprecations/v2.x.html.md
Per items in https://github.com/emberjs/website/pull/2824
* Change `0178` into `#178`
* Move the component lifecycle hook arguments deprecation guide into the 2.12 section (diff shows it as moving an unrelated section in 2.13 :-p)
=> Cleanup ahead of 2.12

Rakefile, static.json
Changes to #2828 
1. The middleman buildpack is redundant. Any ruby app can hook into an asset compilation step by just defining the task `assets:precompile` like Rails does. This just executes the `build` method for building the middleman app.
2. The static buildpack allows variable substitution using env vars using the syntax `${}`. This change lets us set the env var `EMBER_API_DOCS_URL` to any instance we want to proxy to.
I deployed version of ember-api-docs to Heroku where I changed the `rootURL` to be `/api-new/` to match the proxy. Fastboot works, but I ran into issues with pouchdb/couchdb when the JavaScript loads. I've been working with @sivakumar-kailasam to deploy a working version without a dependency on pouchdb: ember-learn/ember-api-docs#146.
Currently, you can see the …
=> Changes to #2828 for Heroku work

Gemfile.lock, Procfile, Rakefile, lib/sponsors.rb, lib/toc.rb, static.json
This begins the migration of the main EmberJS website over to Heroku (https://emberjs-website.herokuapp.com/).  Our Fastboot API viewer is currently being proxied in at (https://emberjs-website.herokuapp.com/api-new/) but `rootUrl` needs to be changed in the api viewer for it to work.
Uses three build packs:
- heroku/ruby
- https://github.com/hashicorp/heroku-buildpack-middleman.git (handles Middleman building)
- https://github.com/heroku/heroku-buildpack-static.git (handles serving built files and proxying)
Things remaining to be done:
=> WIP: Shift main site to run on Heroku

config.rb, static.json
This introduces adding a hash to all the static assets so we can aggressively cache them on the browser. This will also be beneficial for when we move over to a CDN like Fastly, so they should also pick up on it automatically based on the headers.
On the homepage in my test it shaved the transferred data from 1.1 mb (fresh page) to 890 Bytes.
=> Cache Static Assets

source/blog/2017-03-19-ember-2-12-released.md
- [Rendered](https://github.com/emberjs/website/blob/emberjs-release-2-12-0/source/blog/2017-03-13-ember-2-12-released.md).
- Preview.
at: http://emberjs.com/api/classes/ContainerProxyMixin.html#method_factoryFor
- Ember
- Ember Data
- Ember CLI
=> Ember 2.12 blog post

source/blog/2017-03-19-ember-2-12-released.md
Per @Turbo87 https://github.com/emberjs/website/pull/2824#issuecomment-287641138
=> 2.12 blog tweaks

source/stylesheets/_header.scss
[the search icon is missing](https://www.emberjs.com/images/search-icon.svg) on the website. This PR fixes that and replaces occurrences of url attribute with image-url mixin to avoid such issues in the future.
=> Fix broken images

static.json
Now that we handle things on Heroku's end and have LetsEncrypt certs doing this automatically for us ...
=> Redirect all http traffic to https

static.json
Apparently the heroku buildpack will redirect to a raw proxy url instead of shifting to https and then proxying as we'd thought (i.e. when visiting http://www.emberjs.com/api-new folks end up getting redirected to the raw proxy url).
=> Removing http -> https redirect

Gemfile.lock, source/javascripts/app/about/inline-examples.js
Remove deprecated Handlebars SafeString in favor of String htmlSafe
There are issues moving to glimmer2. 
In talk with @acorncom there are plans to move the home page of the ember website to an ember-cli fastboot app in the near future.
=> Update ember source to 2.9

static.json
Per a recommendation from @rwjblue we'll shift to `/api-beta` for the api viewer, makes things clearer
=> Changing our api beta url

source/robots.txt
Doing this so we can keep the api-beta files out of search engine indices until we're ready to launch
=> Disables robot access to our /api-beta folder

source/stylesheets/site.css.scss
Each page on the website results in a different class set on `<body>`. In a few cases, these class names were also used for content on the page. This resulted in some styles affecting more than they should. This PR aims to address one such issue on the Sponsors page.
Summary of this PR:
* Removal of`.sponsors li` -- this was affecting not just the list of sponsors but also the list items in the header nav. The list of sponsors is already styled as it should through the `.showcase` class.
* Removal of `.sponsors ul, .sponsors ol` -- similar to the above, though this actually had no effect on the page at all, as the header-nav overrode these settings for the top list, and `showcase` overrode it for the list of sponsors.
=> Remove over-eager sponsors styling

source/stylesheets/pages/ember-users.css.scss, source/stylesheets/site.css.scss
This moves the styles used to create the rounded shadowed white pill backgrounds from being specific to the Ember Users page to be used for all showcase list links (currently just `/ember-users/` and `/sponsors/` as far as I can tell).
This fixes [the issue reported by @wifelette](https://github.com/emberjs/website/pull/2876#issuecomment-291246130).
=> Extract common styles for Showcase link backgrounds

source/blog/2017-04-05-emberconf-2017-state-of-the-union.md
Since our highlighter doesn’t support TypeScript
=> Use js instead of ts for code samples

source/blog/_sidebar.html.erb, source/javascripts/app/api/toc.js, source/javascripts/app/internal_api/toc.js, source/javascripts/deprecations.js, source/javascripts/toc.js, source/layouts/api.erb, source/layouts/internal_api.erb
should fix https://github.com/emberjs/website/issues/2829
Now we require the `slide-widget-head` on any links that are sliding widgets. The blog sidebar then does not use this class.
=> slide-widget-head required for sliding TOC

source/deprecations/v2.x.html.md
ember's PR: https://github.com/emberjs/ember.js/pull/15204
=> DEPRECATION: Ember.MODEL_FACTORY_INJECTIONS

source/deprecations/v2.x.html.md
In the "Arguments in Component Lifecycle Hooks" section, changed the After example for `didReceiveAttrs` to better match the Before example, and more importantly, to show the manual saving of any properties one might want to compare old values and new values of during `didReceiveAttrs`. More details and link to inspiration for change in #2862
=> Changed example for "Arguments in Component Lifecycle Hooks" deprecation

source/about.html.erb
We're working towards a cleaner look.
Instead of having (outdated) code samples with little context,
we expect interested parties to check out the getting started guide.
We should also make sure the getting started is smooth sailing.
=> Clean up examples in about page

source/stylesheets/site.css.scss
On the users page (`/ember-users`), the users in the leftmost column are missing their left border and the users in the rightmost column are missing their right border. You might have to resize the window width to see it.
This fix just adds a 1px padding to the container so that the borders always show.
=> Fix borders on users

README.md
I removed the reference to Ruby 1.9 and 2.0 because they are too old to run website :<
=> Update Requirements section about Ruby version

.travis.yml
To use the same version as `.ruby-version` in Travis CI.
> If the ruby version is not specified by the rvm key as described above,
> Travis CI will consult `.ruby-version` in the root of the
> repository and use the indicated Ruby runtime.
Ref: https://docs.travis-ci.com/user/languages/ruby/#Using-.ruby-version
=> Remove `rvm` section from `.travis.yml`

Gemfile, Gemfile.lock
They are unnecessary since https://github.com/emberjs/website/commit/2b192878e77816d8274a2179e00aa4c9e7ca4c98
=> Drop unused gems

source/layout.erb, source/stylesheets/site.css.scss
Although they are components to be used in Emberjs family of web resources, the package is prefixed "glimmer" because the components are implemented in Glimmerjs.
We are using the web component shim for easy integration.
=> Extract footer to glimmer-styleguide

data/meetups.yml
This adds @Bestra to our list of Columbus Meetup organizers and updates the avatar URLs for myself (fixing broken reference) and @jmar910 (consistently using smaller filesize)
=> Update Columbus meetup organizers

app.json
This creates a new loader.io addon every time a Review App is created on Heroku. We should probably not do that since we don't need it for review apps.
=> Remove loader.io addon

source/learn/examples.html.erb
The goal is to move them from the Learn page to a dedicated one.
The Learn page will be restructure to feature a sort of three-track learning scheme, so you can pick the one that better adjusts to your learning style.
[Review App](https://ember-website-pr-2956.herokuapp.com/learn/examples/)
=> Add examples page

source/community.html.erb
EmberWatch hasn't been updated in a long time. Ember Weekly is a better community resource.
=> Replace EmberWatch with Ember Weekly

source/blog/2017-08-14-ember-2-15-released.md
First pass at ember-cli-update instructions. I put it first because otherwise it seems like people would go through the old update instructions before seeing that there was a new way if I put it after.
=> ember-cli-update instructions

source/blog/2012-12-22-this-week-in-ember-js-3.markdown, source/blog/2013-02-15-ember-1-0-rc.html.markdown, source/blog/2013-03-30-ember-1-0-rc2.markdown, source/blog/2013-05-28-ember-1-0-rc4.markdown, source/blog/2013-12-17-whats-coming-in-ember-in-2014.md, source/blog/2014-03-30-ember-1-5-0-and-ember-1-6-beta-released.md, source/blog/2014-12-08-ember-1-9-0-released.md, source/blog/2014-12-23-ember-1-9-1-released.md, source/blog/2015-02-07-ember-1-10-0-released.md, source/blog/2015-05-10-run-up-to-two-oh.md, source/blog/2015-05-21-ember-data-1-0-beta-18-released.md, source/blog/2015-06-12-ember-1-13-0-released.md, source/blog/2015-06-18-ember-data-1-13-released.md, source/blog/2015-11-16-ember-2-2-released.md, source/blog/2016-01-12-ember-data-2-3-released.md, source/blog/2016-01-15-ember-2-3-released.md, source/blog/2016-03-13-ember-data-2-4-released.md, source/blog/2016-04-28-baseURL.md, source/blog/2016-05-03-ember-data-2-5-released.md, source/blog/2016-07-25-ember-data-2-7-released.md, source/blog/2017-04-05-emberconf-2017-state-of-the-union.md, source/deprecations/ember-data/v2.x.html.md, source/deprecations/v1.x.html.md, source/deprecations/v2.x.html.md, source/stylesheets/highlight.css.scss
* Fix code syntax highlighting on non-blog pages. They now properly render code blocks with a file name.
* Clean up many code block languages, either use a file name or use a language where proper.
* Use `handlebars` instead of `hbs`.
=> Clean up code snippets, fix highlighting

source/blog/2017-09-01-ember-2-15-released.md
Hey, I noticed this link was the same as the previous one, I think it probably was meant to be a link to the announcement. 😀
=> Correct link to PhantomJS maintenance announcement

source/deprecations/ember-data/v2.x.html.md
* Store.serialize deprecation was in 2.11 (https://www.emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_deprecations-in-ember-data-2-11)
* JSONSerializes.shouldSerializeHasMany was in 2.12  (https://github.com/emberjs/data/commit/388c475c776860b15be05dc49ad8a883bc834bce) although the blog post and changelog don't seem to reflect this https://www.emberjs.com/blog/2017/03/19/ember-2-12-released.html#toc_deprecations-in-ember-data-2-12
* Unused initializers was in 2.13 (https://www.emberjs.com/blog/2017/04/29/ember-2-13-released.html#toc_deprecations-in-ember-data-2-13 https://github.com/emberjs/data/commit/223767fa0011cb0e6e84e15997e8470b3dfa6d2f)
* Change all deprecations in "pending features" to 4.0. This will also need to be done in the Ember-Data codebase.
=> Update Ember-Data Deprecations

source/stylesheets/blog.css.scss
Intended to resolve issue #3004 
**Updated css for blog to normalize with the guides section:**
- switched typography back to Helvetica
- normalized font-sizes and line-height
- normalized h2 margin-top (should help resolve some vertical rhythm issues)
Attached is a screenshot of what the changes should look like when rendered in the browser (compared to the Guides section):
Other work to-do: 
- normalize headers across the site to use uniform colors and margins; remove use of !important
=>  Blog typography update

source/stylesheets/base/_variables.scss
Since iOS doesn't render Google Fonts very well at all, putting Helvetica Neue first should help resolve some issues where Source Sans Pro looks great on any other device but iOS.
=> Put Helvetica Neue back in for better iOS

source/blog/2017-10-11-ember-2-16-released.md
- [Rendered](https://github.com/emberjs/website/blob/2-16-release-blog-post/source/blog/2017-09-09-ember-2-16-released.md)
- Preview
- Ember
- Ember Data
- Ember CLI
- Ember API Docs
=> Ember 2.16 Release Blog Post

source/blog/2017-10-11-ember-2-16-released.md
With the current link situation https://emberjs.com/api works while https://emberjs.com/api/ember does not.
Lets change the link in the blog post so people can see the new docs...
=> change api docs link in blog post to one that works

config.rb
addresses: https://github.com/emberjs/website/issues/3018
looks like middleman just doesn't want to deal with urls in meta tags.
though based off this: https://docs.datocms.com/middleman/seo.html there may be a gem or something to more properly handle fingerprinted full-url assets ref'd in meta.
=> remove the two tomster images from the asset_hash for social use.

source/learn.html.erb, source/stylesheets/learn.css.scss
I have followed the same styles that are present on the guides page to fix this. Added some padding to `ul` in articles within the `.learn` class so we do not worry about any headaches! 
As a result, the list on the learn page is now consistent and inline with the rest of the content. Screenshots included of before and after adding these changes :)
BEFORE
AFTER
Let me know if there are any issues! This project is fun to work on and love the new font! :)
=> List on 'Learn' page cuts in to side of page on mobile devices

source/stylesheets/blog.css.scss
Removes an extra font-family on the blog. With this change, it'll use Source Sans Pro, like the rest of emberjs.com.
=> Fix wrong font-family on blog

source/stylesheets/components/call-to-action.css.scss
**Changes Made:**
- set the CTA so it doesn't take up the full-width on mobile. 
- set the CTA box at an increased width on desktop (350px -> 425px)
- made the heading text a darker gray for better contrast
- increased the font-size, padding and overall width for the CTA button
- alpha-sorted CSS properties
- increased the font-size & adjusted the line-height for the CTA text
- updated the CSS so the bottom of the CTA shows on mobile (it was being hidden)
**Screenshots:** 
Desktop view: 
Mobile view:
=> updated call to action on home page

source/ember-users.html.erb, source/stylesheets/base/_typography.scss, source/stylesheets/pages/ember-users.css.scss, source/stylesheets/site.css.scss
Made some small tweaks based on team feedback: 
- removed uppercase for h2
- removed bottom padding for h1 (the margin is fine)
- removed background color from user logos (left the border and the hover shadow)
- removed text-transform:capitalize from the h1
- added a ".no-capitalize" class to the ember-users h1 just in case someone changes the CSS again before we have the chance to clean it up.
=> small style tweaks based on team feedback

source/stylesheets/pages/about.css.scss
- alpha-sorted the CSS properties
- added a max-width to contain the slider on smaller screens
- added media queries for the user images but this probably won't work, we should really just update the slider (newer versions are responsive) if we can't replace it immediately.
=> updating slider css to be contained on mobile devices

data/showcase.yml
Ran across this text the other day on the learn page and felt it was a bit of false advertising since we never completed pwa support in api docs.  we may get there someday but we ran into issues with api docs being a proxied host to emberjs.com, and the rfc176-driven redesign took higher priority.
=> Remove reference to api doc being a good pwa example

source/blog/index.html.erb, source/layouts/blog.erb, source/stylesheets/base/_typography.scss, source/stylesheets/base/_variables.scss, source/stylesheets/blog.css.scss, source/stylesheets/guides.css.scss, source/stylesheets/pages/blog.css.scss
This PR resolves #3103 
- removed extra h1-h6 styling
- added h1 to blog page 
- removed gray color values and replaced with variable (consistency) 
- removed extra specificity for items that already had a specific enough class name. 
- removed classes that were defined in multiple files (kept only one definition)
- added some scoped styles to differentiate between main blog page and individual posts page(s).
Screenshot of blog page: 
Screenshot of "Recent Posts": 
Screenshot of individual blog post page:
=> Issue 3103 - normalize styling for blog

source/stylesheets/base/_variables.scss, source/stylesheets/site.css.scss
- font family declaration was in the wrong order, causing a mismatch between apple devices and everything else. 
- put them in the correct order; confirmed that it looks as intended on a macbook.
=> font mismatch on apple devices

source/blog/2018-01-01-ember-2-18-released.md
- [Rendered](https://github.com/emberjs/website/blob/2-18-release-blog-post/source/blog/2018-01-01-ember-2-18-released.md)
- Preview
- Ember
- Ember Data
- Ember CLI
=> Ember 2.18 Release Blog Post

source/stylesheets/components/ember-button.css.scss, source/stylesheets/pages/mascots.css.scss
- resolved the issue where the mascot title links where getting a border-bottom instead of an underline on hover. The border-bottom usually works but doesn't here because of the way the link space is bigger than the text 
- updated the ember-button styling (used when links want to look like buttons) to use ember orange
- resolved the issue where these links-as-buttons were getting link treatment on hover instead of button treatment
=> updating some specific link styling

source/learn.html.erb
=> Make the learning resources text be actual links, not just the symbol #3141

source/deprecations/v2.x.html.md
=> Document `currentWhen` deprecation

source/stylesheets/components/ember-conf.css.scss
Resolves #3164 
How it looks with the new color:
=> Improved color contrast on Emberconf CTA button background

source/deprecations/index.html.md, source/deprecations/v3.x.html.md, source/learn.html.erb
- Add page for Ember 3.x deprecation guides
- Add deprecation guide for propertyWillChange and propertyDidChange.
- See emberjs/ember.js#16175.
=> 3.x deprecation guides

source/deprecations/v3.x.html.md
Adds a deprecation for getting `@each`.
Depends on https://github.com/emberjs/ember.js/pull/16215 being merged first.
=> Add deprecation for ember-metal.getting-each

data/tomsters.yml
I noticed this when I was looking into some SEO stuff, it came up as a crawl error
=> Fixing bad link

source/blog/2018-02-14-ember-3-0-released.md
- [Rendered](https://github.com/emberjs/website/blob/3-0-release-blog-post/source/blog/2018-02-14-ember-3-0-released.md)
- Preview
- 3.1-beta blog post: https://github.com/emberjs/website/pull/3187
- Ember
- Ember Data
- Ember CLI
=> Ember 3.0 Release Blog Post

source/stylesheets/blog.css.scss
The ul/li were not allowed to wrap and their overflow was hidden.
This resulted in content being cut and inaccessible on mobile and desktop.
This commit tries to fix the issue. It allows `code` content in `li` to wrap to also prevent overflow on mobile that would cause the annoying result of "the page scrolls horizontally".
I could not find a `li code` example that was broken by this. If you find one I'd be happy to find a better solution. In the meantime this allows for the Ember 3.0 release post to be readable.
:heart:
EDIT: The issue fixed by this PR was just fixed on master. The "the page scrolls horizontally" point is still valid though.
=> Fixing the ul/li rendering in Blog posts

source/blog/2018-02-14-ember-3-0-released.md, source/blog/2018-02-16-ember-3-1-beta-released.md
Follows the 3.0 release blog post: https://github.com/emberjs/website/pull/3149
[Rendered](https://github.com/mixonic/website/blob/blog-3-1-beta/source/blog/2018-02-16-ember-3-1-beta-released.md)
[Preview](https://ember-website-pr-3187.herokuapp.com)
=> Ember 3.1-beta Release Blog Post 

source/deprecations/v3.x.html.md
This is the deprecation text to go with RFC 297 ("Deprecation of Ember.Logger") currently a PR on emberjs/ember.js. I'm entertaining feedback on the text now, but it shouldn't be merged until that PR is also merged.
=> RFC#297 | Ember.Logger deprecation

source/community.html.erb
First pass at fixing #3217 . This just cleans up that section and makes it more apparent where the help is.
=> Clean up Community Help Links

source/ember-users.html.erb, source/stylesheets/pages/ember-users.css.scss
Fixed the naming of the ember users CSS because it conflicted with the CSS on the learn page and it was making things look all wonky.
=> fixed a css bug

source/javascripts/blog.js, source/layouts/blog.erb
Mostly the same setup as in [this fix for the deprecations page](https://github.com/emberjs/website/commit/8af3ebc5aa0a796b5feeb9e5d118c3a4f7a03be7) and closes #3233
=> fix(blog): adds toc links to the blog pages

source/learn.html.erb
We can do better from a marketing perspective than this:
> Over the course of the years cruft inevitably sneaks into all software projects. 
Proposed changes:
I removed the extended links to different versions. With the new app and nicer landing page, I don't think they're necessary.
Sister PR in the deprecations app https://github.com/ember-learn/deprecation-app/pull/112
=> clean up messaging around deprecations on the learn page

data/team.yml, source/stylesheets/base/_typography.scss, source/stylesheets/pages/teams.css.scss, source/team.html.erb
**Done:**
- updated the data so names can be sorted by last name
- separated teams into section
- removed subteams reference, replaced it with team name headings
- added Github and twitter to everyone
- removed team badges (team headings take care of it)
**Still to do:** 
- Ember CLI (@kategengler @kellyselden @Turbo87) 
- Ember Data (@dgeb @igorT)
- Learning Team (@locks @jenweber @acorncom)
=> update to the teams page

source/_footer.html.erb
The social icons in the footer have `:hover { text-decoration: underline }` inherited from base `a` styles. But because the icon links are inline, the whitespace in the html source around the `<i>` icon tags shows up as underlined text on hover.
This removes that whitespace from the html source, ensuring no errant lines show up on hover.
**Before**
**After**
=> Fix hover state of social icons

source/blog/2018-03-26-ember-3-1-released.md, source/stylesheets/base/_typography.scss, source/stylesheets/blog.css.scss
- [Rendered](https://github.com/emberjs/website/blob/3-1-release-blog-post/source/blog/2018-03-26-ember-3-1-released.md)
- Preview
- Ember
- Ember Data
- Ember CLI
=> Ember 3.1 Release Blog Post

source/blog/2018-04-01-the-emberjs-times-issue-43.md, source/stylesheets/pages/blog.css.scss
This publishes the upcoming edition of the [Ember.js Times](https://the-emberjs-times.ongoodbits.com/) to the blog.
This should be released until Friday, April 20, 22 h UTC the latest and be cross-linked through the Ember.js Times newsletter accordingly
=> release(blog): The Ember.js Times - Issue #43

source/javascripts/app/docsearch.js.erb
For anyone who doesn't know the context of this change: as discussed on today's learning team meeting we need to temporarily disable API search results on the website because of issues with our index. There are separate efforts trying to fix that and we can re-enable API search on the website if any of those efforts pay off.
=> temporarily removing API search from the website

source/blog/2018-04-01-the-emberjs-times-issue-43.md
UPDATE: Feel free to pass on this for the April 20 edition if there is not time, it can go in next week also!
Never mind, unstaged it:
~~Aside: it seems like my `.editorconfig` is making some whitespace changes to copy I didn't touch as well. Can fix if undesired.~~
=> Add Ember Learn update for Ember Times 43 or 44

source/blog/2018-05-18-the-emberjs-times-issue-47.md
Kept this under `Ember Learn` for now, since @jessica-jordan mentioned some other content that I think will go there too...
=> Ember Times #47: Add call for blog posts

source/blog/2018-05-18-the-emberjs-times-issue-47.md
To be released on May 18th, 2018.
[Rendered](https://github.com/emberjs/website/blob/91cf20230f2b9d625f0a7c1d0f1e75cabbaba3f7/source/blog/2018-05-18-the-emberjs-times-issue-47.md)
Staging App: https://ember-website-staging-pr-3339.herokuapp.com/blog/
This week's topics include:
- New Ember Data RFC: https://github.com/emberjs/rfcs/pull/332
- re-mention Ember Data RFC for Evented Deprecation: https://github.com/emberjs/rfcs/pull/329
- New Guides App released 🤞 
- 2 weeks left for Ember roadmap 2018 blog posts
- Ember Template Recast: https://github.com/ember-template-lint/ember-template-recast
- Ember CLI Addon Docs Updates:
> ember-cli-addon-docs has been getting a lot of love lately. Ember decorators recently revamped their docs(http://ember-decorators.github.io/ember-decorators/latest/) …
=> Release Ember.js Times Issue #47

source/sponsors.html.erb, source/stylesheets/pages/sponsors.css.scss
If merged, this would fix the sponsors page. 
Current:
Fixed:
=> bug: sponsors page

source/blog/tag.html.erb
Removed a misplaced semicolon that was preventing the tag.html.erb from rendering responsively.
=> removed misplaced semicolon

README.md
Fix #3330 
Do not merge until the launch day!
=> [Guides App Launch] Update links in README.md file to point to new Ember Guides repo

source/blog/2018-05-25-the-emberjs-times-issue-48.md
@jessica-jordan 
cc @mansona @jenweber this is mostly from the README and Slack channel chatter, feel free to make any edits re: the new guides
=> Amy's adds to Ember.js Times #48

source/blog/2018-05-25-the-emberjs-times-issue-48.md
This week's topics include:
- (eventually) New Guides App released 🤞
- 1 week left for Ember roadmap 2018 blog posts
- Ember CLI Addon Docs Updates (Miguel):
> ember-cli-addon-docs has been getting a lot of love lately. Ember decorators recently revamped their docs(http://ember-decorators.github.io/ember-decorators/latest/) using https://ember-learn.github.io/ember-cli-addon-docs/latest/, might be worth featuring ember-cli-addon-docs again.
Feel free to add further topics to the comments below or mention any that you find interesting at #topic-embertimes
=> Release Ember.js Times Issue #48

source/blog/2018-05-18-the-emberjs-times-issue-47.md
With the new categorization feature of blog posts that has been launched through https://github.com/emberjs/website/pull/3280 the Ember.js Times now has their own dedicated post category. 
This moves the Issue No. 47 which was just launched last week away from the more general `Recent Posts` section and makes it only show up in the dedicated embertimes section instead.
| **before** | **after** |
|------------|----------|
| <img width="311" alt="screen shot 2018-05-25 at 08 42 22" src="https://user-images.githubusercontent.com/8811742/40530081-b61b23ec-5ff7-11e8-9543-2e6ef7624774.png">| <img width="336" alt="screen shot 2018-05-25 at 08 42 04" src="https://user-images.githubusercontent.com/8811742/40530096-c06030ae-5ff7-11e8-80e8-c0b3d0d7b627.png"> |
=> Remove Ember.js Times #47 from Recent Posts Category

source/blog/2018-05-18-the-emberjs-times-issue-47.md, source/blog/2018-05-25-the-emberjs-times-issue-48.md
The most recent Ember Times should have the Recent Post tag, older editions should have it removed
- added "Recent Post" tag to the most recent Ember Times post
- removed "Recent Post" tag from the previous edition
=> updated tags

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This adds templates that are used when opening new Github issues or pull requests. See also the [documentation on Issue / PR templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/).
| Issues | PRs |
|-------|-----|
| ![imhavingissues](https://user-images.githubusercontent.com/8811742/40749924-edb4dda8-6465-11e8-9fa1-144aba4feef4.gif)| ![imhavingprs](https://user-images.githubusercontent.com/8811742/40750322-32ccc1d4-6467-11e8-97f0-aba4d9312afd.gif)|
=> Add Issue and Pull Request Templates

source/logos.html.erb
Fixes a typo in the usage description on the logos page.
=> Add 'for' into sentence about logo usage in `logos.htmls.erb`

source/blog/2018-06-15-the-emberjs-times-issue-51.md
Adds Component#isVisible deprecation write-up
=> Adds Component#isVisible deprecation

source/blog/2018-06-15-the-emberjs-times-issue-51.md
This adds the following content to Issue No. 51 of the Ember Times:
- Future of Ember, highlighting @chrism's blog post
- Intro
- Generic Readers' Question section
- Ember Engines Roadmap
- le contributors
=> Blog(embertimes#51): Fill in the rest

source/blog/2018-06-15-the-emberjs-times-issue-51.md
This is the blog post format of the upcoming edition of the Ember.js Times - Issue 51. This should be released on Friday, June 15th.
-  "Future of Ember": AngleBracketInvocation Components & Named Args with two new polyfills to use these features already today
-- https://twitter.com/rwjblue/status/1004470433872216064
-- https://twitter.com/rwjblue/status/1003070244204793856
- RFCs in FCP: Component#isVisible and Component#sendAction:
-- https://github.com/emberjs/rfcs/pull/324
-- https://github.com/emberjs/rfcs/pull/335
- "Future of Ember": Experimenting with current feature flag features: https://medium.com/@chrisdmasters/emberjs2018-my-safari-into-the-future-e4f31a4902ea
- Ember Engines Roadmap 1.0: https://discuss.emberjs.com/t/engines-1-0-roadmap/14914
...
Feel free to add further …
=> Release Ember.js Times No. 51

source/about.html.erb, source/layout.erb, source/stylesheets/about.css.scss, source/stylesheets/base/_typography.scss, source/stylesheets/pages/about.css.scss
If merged, this pull request would make the following changes: 
- updates "Get Started" to "Try it out!" 
- makes the h2 larger and tweaks the margins
- changes "More productive out of the box" to "Highly productive out of the box" 
- updated the text in the productivity section
- made these feature sections a little wider on larger screens (they still stack on smaller viewports)
- changed the "donate" button to "buy ember gear" (the header language and button CTA text was too discordant)
This would also lead to future work- the intend is to add some additional information to each productivity feature, like this:
=> Incremental updates to home page

source/about.html.erb, source/stylesheets/about.css.scss, source/stylesheets/pages/about.css.scss, source/stylesheets/site.css.scss
If merged, this PR will implement the following: 
- updates vertical spacing on contribute call to action above footer
- adds "buy ember gear" in addition to "donate" button
- fixes the issue where the handlebars feature text started higher than the other text (I would have done a more elegant job at fixing this if we weren't emberizing the website this week)
=> Home page updates

source/blog/2018-06-22-the-ember-times-issue-52.md
Adds Native Class Constructor Update write-up to blog
=> Adds Native Class Constructor Update write-up to blog

source/blog/2018-06-22-the-ember-times-issue-52.md
See also the wording from [the original RFC](https://github.com/pzuraq/emberjs-rfcs/blob/94b38d429eb2964fa86cd13bea6823a01b3ef68d/text/0000-native-class-constructor-update.md):
> One thing we should make clear is that EmberObject will likely be deprecated in the near future, and that ideally for non-Ember classes (things that aren't Components, Services, etc.) users should drop EmberObject altogether and use native classes only.
I changed it up a bit so it sounds less set into stone.
=> blog(embertimes#52): add more emphasis on the possible depr. of E.Obj

data/team.yml, source/blog/2018-06-30-organizing-our-contributors.md, source/stylesheets/pages/teams.css.scss, source/team.html.erb
This PR adds the "organizing our contributors" blog post and updates the team page to reflect the new organization. 
team data: 
- changed `corealumni` to `alumni`
- change `core` to `corejs`
- added alumni status to ember-cli team members as per that team
- added `steering` as appropriate
team page: 
- added "Core" designation to all teams
- added the Steering Committee 
- updated the template code for consistency
- alphabetically sorted teams by last name (except the steering committee)
- re-wrote the CSS to use flexbox 
blog post: 
- added the "Organizing Our Contributors" blog post (dated 6/30/18)
=> organizing our contributors blog post

source/blog/2018-04-20-the-emberjs-times-issue-43.md, source/blog/2018-04-27-the-emberjs-times-issue-44.md, source/blog/2018-05-04-the-emberjs-times-issue-45.md, source/blog/2018-05-11-the-emberjs-times-issue-46.md, source/blog/2018-05-18-the-emberjs-times-issue-47.md, source/blog/2018-05-25-the-emberjs-times-issue-48.md, source/blog/2018-06-01-the-emberjs-times-issue-49.md, source/blog/2018-06-08-the-emberjs-times-issue-50.md, source/blog/2018-06-15-the-emberjs-times-issue-51.md, source/blog/2018-06-22-the-ember-times-issue-52.md
Replaces instances of the Ember.js Times to the Ember Times. 
Closes #3410
=> issue #3410 - renamed the Ember.js Times to the Ember Times

source/blog/tag.html.erb, source/layouts/blog.erb, source/stylesheets/blog.css.scss
This uses the Ember Times Logo and places it as a header item into the newsletter and Ember Times overview pages. It also adds the logo as a header item into each single Ember Times post that has been tagged as `Newsletter`.
To be discussed: On the tag page I decided to hide the heading `Newsletter` via `visibility:hidden` and include the image together with `Ember Times` as an `alt` attribute in the same `h1` tag.
If this isn't sufficient to provide a great a11y experience, I can improve it as suggested.
See also the screenshot and the screen recording below.
Visit on the following routes on your local instance:
- Tag Pages: http://localhost:4567/blog/tags/newsletter.html and http://localhost:4567/blog/tags/ember-times.html
- Post Page, e.g. …
=> Add Ember Times Logo to Tag Page and Ember Times Posts

source/blog/2018-06-29-the-ember-times-issue-53.md
This removes the Ember Times No.53 from the list of recent blog posts. This should be merged once edition 54 is released.
Relates to #3438
=> blog(embertimes): remove issue 53 from recent posts

source/stylesheets/about.css.scss
Line height and text size are typically inverses, so I'm proposing we take down the line-height of the title a bit.
Happy to provide some material on this if anyone would like!
=> Reduce line-height of title

source/blog/2018-07-13-requiring-2fa-for-github-org-members.md
Add a blog post to announce our policy on 2factor auth for our github orgs
=> Add blog post announcing requirement of 2-factor auth

source/blog/2018-07-13-the-ember-times-issue-55.md
This Goodbits link has a different pattern than https://the-emberjs-times.ongoodbits.com/2018/07/06/the-ember-times-issue-54 or https://the-emberjs-times.ongoodbits.com/2018/06/29/the-ember-times-issue-53. Should we fix here or on Goodbits?
=> Update broken link

source/_header.html.erb
Logo was using a relative URL and therefore not being available on any subpage (expect for API docs which is generating header on it's own). This was introduced in 9278d2381788dc607fcef62efe6e92c2953e7ae6.
=> Fixes logo on subpages

source/blog/2018-07-06-the-ember-times-issue-54.md, source/blog/2018-07-13-the-ember-times-issue-55.md
This removes previous editions from the list of recent posts and only leaves the most recent edition (No. 58) up.
=> blog(embertimes): remove issue 55 + 54 from recent posts

source/blog/embertimes-template.md
This adds a template for making it easier to create a new feature branch for each week's Ember Times edition. You can generate a new template from it by copying it in your favorite editor or by using `cp` in the command line as follows:
```bash
// Example: create No. 99 of Ember Times to be released on Jan 1st, 1970
cd website/
cp source/blog/embertimes-template.md source/blog/1970-01-01-the-ember-times-issue-99.md
```
=> blog(embertimes): Adds ember times template

source/blog/embertimes-template.md
Sometimes the Goodbits had a different URL, but am not certain of the cause.
What do you think about changing https://www.emberjs.com/blog/xxxx/xx/xx/the-ember-times-issue-XX.html to https://emberjs.com/blog/tags/newsletter.html so we don't have to update it every time / less prone to error?
=> Update Ember Times template 

source/blog/2018-08-31-the-ember-times-issue-62.md
This might be a bit too long? Not sure where to cut it or if I maybe need to add more?
=> Add section on Module Unification Packages

data/users.yml
Removes InQuicker from the list of Ember Users
I added InQuicker to the Users list when I worked there and we were actively advancing Ember development within the product and company. Sadly, our team has disbanded and there is no longer active Ember development going on within InQuicker.
=> Remove InQuicker from Users

source/blog/2018-09-07-the-ember-times-issue-63.md
[rendered](https://github.com/chrisrng/website/blob/4f90ef1645162e3738296ddb15807e2b47f685b8/source/blog/2018-09-07-the-ember-times-issue-63.md#new-computed-property-rfcs-deprecating-volatile-and-readonly-2%EF%B8%8F%E2%83%A3)
=> blog(embertimes#63): 2 RFCs for Computed Props

source/blog/2018-09-07-the-ember-times-issue-63.md
* Incorporate edits from #3550
* Add Ember Data RecordData META QUEST, relates to: emberjs/data#5618
=> [Ember Times] Amy RecordData writeup

source/blog/2018-08-31-the-ember-times-issue-62.md, source/blog/2018-09-07-the-ember-times-issue-63.md
=> The Ember Times - Issue No. 63

source/blog/2018-09-14-the-ember-times-issue-64.md
[rendered](https://github.com/chrisrng/website/blob/chrisrng-patch-1/source/blog/2018-09-14-the-ember-times-issue-64.md#element-modifier-rfcs-%EF%B8%8F)
=> blog(embertimes64): Element Modifier RFCs

source/blog/2018-09-07-the-ember-times-issue-63.md, source/blog/2018-09-14-the-ember-times-issue-64.md
=> The Ember Times - Issue No. 64

source/blog/2018-09-21-the-ember-times-issue-65.md
[rendered](https://github.com/chrisrng/website/blob/7351fbab192c79aaf17abccf767c82e7fc4215cb/source/blog/2018-09-21-the-ember-times-issue-65.md#published-sparkles-component-110-)
=> blog(embertimes65): sparkles-component 1.1.0

source/blog/2018-09-21-the-ember-times-issue-65.md
Relates to: https://github.com/emberjs/website/pull/3566
The build for https://github.com/emberjs/website/pull/3566 passed, but when it was merged into https://github.com/emberjs/website/pull/3563 it failed
=> [Ember Times] Add alex linter ignores

source/blog/2018-09-21-the-ember-times-issue-65.md
=> For Ember Times No. 65: Add Contributors, property RFC, Editors

source/blog/2018-09-14-the-ember-times-issue-64.md, source/blog/2018-09-21-the-ember-times-issue-65.md
=> Ember Times Issue 65

source/blog/2018-09-28-the-ember-times-issue-66.md
Add section to `[WIP] Ember Times Issue 66`, #3577
Adds a section to issue 66 of Ember Times for Issue Triage effort for the past 2 weeks.
Merges into branch for #3577
=> Add section on Issue Triage efforts the past 2 weeks

source/blog/2018-09-28-the-ember-times-issue-66.md
[rendered](https://github.com/chrisrng/website/blob/8555e3458c2209fc021eaff54d13b56a8a004168/source/blog/2018-09-28-the-ember-times-issue-66.md#ember-cli-deprecation-workflow-100-release-)
=> blog(embertimes66): ember-cli-deprecation-workflow

source/blog/embertimes-template.md
no need to review until the issue is out
=> [embertimes] workshop "about ember times" template

source/community.html.erb
I think we have a lot of messaging to do over the coming 6-12+ months about the move to Discord, so I thought it would be helpful to add a pointer for someone grep'ing the site for Slack.
=> Add link to Slack -> Discord RFC

source/community.html.erb
This PR updates two discord links on Ember Community Page.
To see the _error_ at image below:
Closes #3593
=> Fixes discord links on community page (#3593)

source/blog/embertimes-template.md
I recently learned you can link to a Discord channel if you go to the Discord web version. (I'm also updating this in my PR for upcoming issue # 67.)
=> [embertimes] Update template

source/blog/CONTRIBUTING.md
[rendered](https://github.com/chrisrng/website/blob/bddc800476cc3ec0b54a4de5d3dc949f90e23052/source/blog/CONTRIBUTING.md)
Changes:
- How to ignore alex linter
- Add emoji to title
- `addon` as a word
=> docs(blog contributing): updates for alex linter, emoji title, addon word

source/blog/2018-09-28-the-ember-times-issue-66.md, source/blog/2018-10-05-the-ember-times-issue-67.md
- a good example of what needs to be done on the 977 repos https://github.com/ember-cli/ember-cli/blob/master/package.json#L25-L28
- There's more info here: https://docs.npmjs.com/files/package.json#repository If a repo is on github, a shorthand can be used ala `"repository": "ember-cli/ember-cli"`
=> Ember Times Issue 67

source/blog/2018-10-07-ember-3-4-released.md
Prelude has wording "There is one (1) new feature, three (3) deprecations" but respective sections have titles "New Features (2)" and "Deprecations (2)"
=>  Update number of features and deprecations in prelude in Ember 3.4 blog post

source/blog/2018-10-07-ember-3-4-released.md
The 3.4 blog post refers to "creating component bases classes", but I think the intent was "creating component _base_ classes". This PR fixes the typo.
=> Typo in 3.4 post: 'bases classes' -> 'base classes'

source/blog/2018-10-19-the-ember-times-issue-69.md
=> For EmberTimes No. 69: Add Section about Relationship Loading RFC

source/blog/2018-10-19-the-ember-times-issue-69.md
Also, added authors and cleaned up the branch
Still need:
=> Short writeup on EmberConf brainstorm

source/blog/2018-10-19-the-ember-times-issue-69.md
[rendered](https://github.com/emberjs/website/blob/0662bd783d4f3360c3dd8514d40a9658f6ceb48f/source/blog/2018-10-19-the-ember-times-issue-69.md#new-addon-release-ember-self-focused-%EF%B8%8F)
=> blog(embertimes69): ember-self-focused

source/blog/2018-10-12-the-ember-times-issue-68.md, source/blog/2018-10-19-the-ember-times-issue-69.md
Ideas, feel free to add to list or claim:
Ideas we are waiting on:
=> Ember Times Issue 69

source/about.html.erb, source/stylesheets/pages/about.css.scss, source/stylesheets/pages/resources.css.scss
Make users section responsive, remove carousel and improve spacing. Show 8 users on desktop and 4 on mobile.
Just making a few small improvements for Hacktoberfest 🎃 
Fixes #3134
=> Frontpage improvements

data/meetups.yml
After EmberConf 2018, I met with the previous organizers and became the sole organizer for Ember Dallas (as seen at https://www.meetup.com/Ember-Dallas/events/past/)
Remove previous Ember Dallas organizers and add myself
N/A
N/A
=> Add Tony Ward as the Ember Dallas meetup organizer

source/blog/2018-10-26-the-ember-times-issue-70.md
=> For EmberTimes No. 70: Router Helpers & setComponentManager RFC writeups

source/blog/2018-10-26-the-ember-times-issue-70.md
[rendered](https://github.com/emberjs/website/blob/3b41b6e3a005cbd8eafe3213c3d377a86200a73c/source/blog/2018-10-26-the-ember-times-issue-70.md#ember-i18n-deprecation-and-release-of-ember-intl-)
For https://twitter.com/MiguelCamba/status/1054699605865177089
=> blog(embertimes70): ember-i18n to ember-intl

source/blog/2018-10-26-the-ember-times-issue-70.md
Not sure if to add myself as an author this week 😅 
Just did a tiny bit of editing
=> Grammar fixes

source/blog/2018-11-02-the-ember-times-issue-71.md
=> For EmberTimes No. 71: Add Tree-Shaking Help Wanted CTA

source/blog/2018-11-02-the-ember-times-issue-71.md
=> Add hello, authors and fixed some grammar

source/blog/2018-11-02-the-ember-times-issue-71.md
=> Add section on Ember Route Actions RFC

source/blog/2018-11-09-the-ember-times-issue-72.md
https://github.com/emberjs/website/blob/f216b54ffadd6050364e0443489e87f06121e62c/source/blog/2018-11-09-the-ember-times-issue-72.md#jsconf-eu-cfp-is-now-open-
=> blog(embertimes72): JSConfEU CFP

source/blog/2018-11-09-the-ember-times-issue-72.md
=> For EmberTimes 72: Add Writeup on RouteInfo Metadata RFC

source/blog/2018-11-16-the-ember-times-issue-73.md
=> For EmberTimes No. 73: EmberConf CfP + Ember Hooks

source/blog/2018-11-16-the-ember-times-issue-73.md
https://twitter.com/TobiasBieniek/status/1062700572757946368
=> blog(embertimes73): eslint-plugin-ember

source/blog/2018-11-23-the-emberjs-times-issue-74.md
=> Ember in VSCode help wanted writeup

source/blog/2018-11-16-the-ember-times-issue-73.md, source/blog/2018-11-23-the-emberjs-times-issue-74.md
Todos:
Ideas for future week instead:
=> The Ember Times - Issue No. 74

source/blog/2018-11-30-the-emberjs-times-issue-75.md
=> For EmberTimes No. 75: add Contributors + EmberFest Writeup

source/_header.html.erb
I have added the CLI guides to the "Docs" dropdown, and clarified "The Guides" as "Ember.js Guides".
I did not add a link to the CLI Guides API because I think it's ok for someone to get to it via the Guides. The CLI API docs also need some kind of review before they are included in the top navbar.
"The Guides" are really "The Ember.js Guides" because as we make more guides (like Ember Data, Ember CLI, etc) we need more granular descriptions.
These 3 PRs should be merged at the same time:
1. ember-styleguide https://github.com/ember-learn/ember-styleguide/pull/115
2. ember-api-docs https://github.com/ember-learn/ember-api-docs/pull/576
3. website https://github.com/emberjs/website/pull/3705
=> Add CLI guides to the navbar

source/blog/2018-12-07-the-ember-times-issue-76.md
=> Added section on JSON:API 1.1 RC1

source/blog/2018-12-07-the-ember-times-issue-76.md
=> For EmberTimes No. 76: Add Ember CLI ESLint Writeup

source/blog/2018-11-19-ember-3-6-released.md
Adds the 3.6 release information to the release blog post.
=> 3.6 blog post

source/blog/2018-12-07-the-ember-times-issue-76.md, source/blog/2018-12-14-the-ember-times-issue-77.md
Todos:
* Have to move social links to the bottom (above footer)
* Delete extra blank line at the end of each section
* Replace broken image in Readers' Questions with https://emberjs.com/images/tomsters/officehours-42680347.png
=> The Ember Times - Issue No. 77

source/blog/2018-12-17-mentorship-program.md
The `alex` comments were showing up due to their placement in the markdown
=> fix linting comments that showed up in markdown

source/blog/2018-12-21-the-ember-times-issue-78.md
Adding update about Ember Inspector to the times post.
=> Add Inspector Update

source/stylesheets/components/call-to-action.css.scss
reverts the CTA color background change.
- there were not supposed to be any design changes at this point
- no (home page) change should be introduced in a PR with a different/unrelated change
- this version of the site is in freeze (the ember-learn/ember-website launch is soon).
=> revert design change for home page CTA

source/blog/2018-12-14-the-ember-times-issue-77.md, source/blog/2018-12-21-the-ember-times-issue-78.md
Someday:
Todos:
* Updated https://github.com/jessica-jordan/emberjs-times-tools README
=> The Ember Times - Issue No. 78

source/blog/2018-12-14-the-ember-times-issue-77.md
These emojis don't display in Firefox on MacOS, not sure why yet
Will make a staging branch to verify
=> ember times: Remove 0️⃣1️⃣ emojis

source/blog/2019-01-07-ember-3-7.md
=> 3.7 blog post

.alexrc, source/blog/2019-01-25-framework-f2f.md
Adds a new blog post! This content was extensively reviewed by framework core team members while it was in a Dropbox doc, and just needs a quick check from someone with sharp eyes to make sure there are no typos.
It also adds `hooks` to `.alexrc` so that tests won't fail because of this very common word.
Changes from Dropbox:
- gave it a title
- instead of "framework core team," called it "Ember.js Core Team" to align with https://emberjs.com/teams
- linked to teams in the first sentence
- removed a sentence that said something is in FCP (it is now merged)
- three months to go until EmberConf --> two months
=> Ember.js Framework Core Team F2f blog post

data/meetups.yml
This reverts commit f824a4d3f96bd8ad5100aa0e01dc61c44e20d24a.
This changes the location of the Ember Columbus meetup back to our original meeting location as we will be returning there starting with our next meeting: https://www.meetup.com/ember-columbus/events/258995807/
=> Revert Ember Columbus meetup location to original

source/blog/2019-02-19-ember-community-survey.md, source/ember-community-survey-2019.html.erb
Fixes a link in the survey announcement blog post to go to 2019 instead of 2018 😬 
Tweaks some wording on the landing page.
https://github.com/emberjs/website/pull/3823
=> Quick survey announcement fixes

source/blog/2019-02-22-the-ember-times-issue-86.md
=> Add section on Deprecate Partials RFC

source/blog/2019-02-22-the-ember-times-issue-86.md
Like DecEmber, it was easier to just share the blog post text somewhat in full (word for word) here... 😳
=> Add survey writeup to Ember Times

source/stylesheets/blog.css.scss
Modified the style of the h4 in the blog posts to make it easier to digest the information (note- the images make the text size look smaller than it really is). 
Before: 
After:
=> updating h4 style for the blog posts

source/blog/2019-02-27-ember-3-8-released.md
Fix grammar `is two` -> `are two`
Fix s `two feature` -> `two features`
=> Fix grammar in Ember 3.8 Blog Post

source/blog/2019-03-01-the-ember-times-issue-87.md
Added my name in an earlier (open) PR
=> blog(embertimes87): Classic Class Owner Tunnel

source/blog/2019-02-22-the-ember-times-issue-86.md, source/blog/2019-03-01-the-ember-times-issue-87.md
=> Ember Times No. 87 - March 1, 2019

source/blog/2019-02-27-ember-3-8-released.md
It seems that four deprecations were wrongfully tagged as `3.8` instead of `3.9` so I have updated the release post to reflect reality.
=> Remove 3.9 deprecations

source/blog/2019-03-08-the-ember-times-issue-88.md
=> Adds ember survey call to action

source/blog/2019-03-01-the-ember-times-issue-87.md, source/blog/2019-03-08-the-ember-times-issue-88.md
https://www.youtube.com/watch?v=BV09blWlc64 (🔏 @jaredgalanis)
Todos:
=> Ember Times No. 88 - March 8, 2019

source/blog/2019-03-02-update-on-module-unification-and-octane.md
Provides thoughtleadership to the Ember community in the form of a weblog ("blog") post, describing the status of Module Unification and the plan for Octane.
=> [WIP] Adds Module Unification & Octane Update blog post
