data/users.yml
Updated this PR based on the discussion below.
~~Not sure if @mhelabs is still around and active? Maybe @vineet-sinha can chime in? Either way, it's currently a a dead link and being shown on the homepage.  ¯\_(ツ)_/¯~~
=> Update MHElabs link due to it being 404.

source/blog/2015-02-04-ember-1-10-0-released.md
[Read it as markdown](https://github.com/mixonic/website/blob/blog-1.10/source/blog/2014-02-04-ember-1-10-0-released.md)
I appreciate any review and edits! Especially if I have missed a feature or change.
=> Add 1.10 blog post

source/blog/2015-02-07-ember-1-10-0-released.md
Some text and syntax highlighting cleanup.
=> Blog cleanup

source/blog/2015-02-07-ember-1-10-0-released.md
It seems some people are getting hung up on this.
=> Improve upgrade instructions for Ember-CLI users

data/meetups.yml
=> Remove Göteborg meetup

data/meetups.yml
=> Added St.Petersburg meetup

source/guides/configuring-ember/disabling-prototype-extensions.md
Fixes UI issue on the second code example for [this page](http://emberjs.com/guides/configuring-ember/disabling-prototype-extensions/).
I hope this helps.
Thanks!
=> Fix second code example on "Disabling Prototype Extensions" page

source/guides/routing/query-params.md
=> Removed an unneeded whitespace

source/blog/2015-02-14-ember-data-1-0-beta-15-released.md
=> Add a blog post announcing the release of Ember Data 1.0.0-beta.15

source/guides/getting-started/show-when-all-todos-are-complete.md
Without this comma, todos_controller.js fails to parse.
=> fix missing comma for allAreDone property

source/guides/getting-started/toggle-all-todos.md
* Same fix as in #2034 but for the next chapter
=> fix missing comma in javascript snippet for toggle-all-todos.md

source/guides/getting-started/using-other-adapters.md
Fixes https://github.com/emberjs/website/issues/2036 - see discussion there.
=> Issue 2036: Fix localStorage-adapter raw url to version compatible with Ember Data 1.0 beta.11

source/about.html.erb, source/stylesheets/about.css.scss, source/stylesheets/site.css.scss
=> Replace "download" with "npm install -g ember-cli"

source/blog/2014-12-08-ember-1-9-0-released.md
=> Fixed close tag

source/guides/templates/writing-helpers.md
=> Added Ember object

data/meetups.yml
Believe I followed conventions I saw in other pulls, but please let me know if you'd like in a different format or other information!
=> Add EmberJS-Houston

source/stylesheets/site.css.scss
=> Fixes header/footer on small screens

source/guides/deprecations/index.md
For emberjs/ember.js#10583 and emberjs/ember.js#10584
=> Add some deprecations for 1.12

source/community/meetups-getting-started.erb, source/community/meetups.html.erb
=> Fix broken links in meetup and community pages

source/community.html.erb
Recently a Slack thing has started for the ember community.  What better place to spread info about it than here!
=> Add link to EmberJS Community Slack

source/blog/2015-03-27-ember-1-11-0-released.md
[View as HTML](https://github.com/mixonic/website/blob/blag/source/blog/2015-03-27-ember-1-11-0-released.md)
=> Ember 1.11 blog post

source/javascripts/app/builds/app.js
=> List ember-template-compiler.js on builds site.

source/stylesheets/site.css.scss
Same fix as applied in the guides repo :smile:
=> Fix for https://github.com/emberjs/website/issues/2113

Gemfile.lock, source/javascripts/app/examples/components/templates/components/gravatar-image.hbs, source/javascripts/app/examples/loading/templates/application.hbs, source/javascripts/app/examples/routing/templates/application.hbs, source/javascripts/app/examples/routing/templates/mailbox.hbs
So long `bind-attr`
Also updated each helpers to use block syntax.
Also update ember-source to 1.11.0.1. There was an issue with 1.11.0 
Cheers
=> [FEATURE] updated about ember examples to 1.11.0

source/blog/2015-04-20-ie8-support-update.md
I copy and pasted @tomdale's response from the RFC into a blog post. Seems good to officially announce it on the blog; I know not everyone keeps up to date with RFCs or follows us on twitter.
=> blog post for ie8 compatibility in emberjs 2.0

source/blog/2015-05-05-glimmer-merging.md
Please don't merge this until someone has filled in the Upgrading section.
Feedback wanted! [View as HTML](https://github.com/emberjs/website/blob/glimmer-post/source/blog/2015-05-05-glimmer-merging.md)
=> Initial pass at a blog post for Glimmer

source/blog/2015-04-08-ember-1-12-new-features.md
[Rendered](https://github.com/emberjs/website/blob/72ee1fd84c0516e40718a3166051b1a709fbe9e3/source/blog/2015-04-08-ember-1-12-new-features.md)
Summarize the new features in 1.12 so people can try them out, especially the improved computed property syntax.
=> 1.12 New Features

source/blog/2015-05-13-ember-1-12-released.md
The argument `value` looks like a key.
=> Fix example in blog post

data/meetups.yml
Added location and organizer details for new Ember group in Manchester, UK.
=> Ember Manchester meetup in community pages

source/blog/2015-05-21-ember-data-1-0-beta-18-released.md
This is a part of heading, isn't it?
=> Fix heading in blog-post

source/stylesheets/site.css.scss
=> Make the file header styling match the guides.

source/blog/2015-06-05-ember-data-1-0-beta-19-released.md
See https://github.com/emberjs/data/issues/3256
=> Adding note about instance initializer

source/blog/2015-05-13-ember-1-12-released.md
Per confusion in https://github.com/emberjs/ember.js/issues/11247, update the blog post
=> Note that defer is not permitted in instance initializers

source/blog/2015-06-12-ember-1-13-0-released.md
Ref: https://github.com/emberjs/ember.js/pull/11468#issuecomment-112099340
=> Add Freezable to deprecations in blog post

source/about.html.erb, source/javascripts/app/about/inline-examples.js
=> Fixed broken tabs on the about page

source/blog/_sidebar.html.erb
Core team meeting minutes now live at https://github.com/emberjs/core-notes
=> Drop Core Team Meeting Minutes link on blog

source/blog/2015-06-18-ember-data-1-13-released.md
=> Ember Data 1.13 release blog post

source/blog/2015-06-18-ember-data-1-13-released.md
=> Fix a typo 😜

source/blog/2015-06-18-ember-data-1-13-released.md
Change
>If your app is using the vanilla JSONSerializer or RESTSerializer, you will not have to make any changes, and `you` app will continue to work.
to
>If your app is using the vanilla JSONSerializer or RESTSerializer, you will not have to make any changes, and `your` app will continue to work.
=> Fix typo in Ember data 1.13 release blog

README.md
I got a little confused by the instructions for setting up the site, so I'm suggesting some changes that I think might help future devs like myself.
=> Clarify instructions for setting up site locally.

source/blog/2015-06-05-ember-data-1-0-beta-19-released.md
=> Update the Ember Data beta.19 blog post to say Ember Data 1.13 supports IE8

source/javascripts/app/builds/app.js
Fixes https://github.com/emberjs/ember.js/issues/11725
- Problem: tagged v2.x builds were not showing because S3 returns a max
of 1000 builds alphabetically
- Solution: recursively load additional pages if the response's
`isTruncated` field is true
One thing to be aware of is that it sets `response` on the S3Bucket to be the the last response. As far as I can tell `response` is no longer used so it could be removed or left in place.
https://github.com/pdud/website/blob/01dea25589cb0bf5f3376a9a1b53b53ba1c21949/source/javascripts/app/builds/app.js#L144
=> Show tagged builds for v2.x

data/meetups.yml
- Added Louisville, KY to the meetup page
- Added cball to the Boston organizers
=> Added Louisville meetup; Updated Boston Organizers

source/deprecations/v1.x.html.md
This starts some of the deprecations mentioned in #2256
=> Add ArrayController to 1.13 deprecations

source/javascripts/app/builds/app.js
Currently not updated on the website, since it says 1.13.6
=> Update ED release to 1.13.7

data/users.yml, source/ember-users.html.erb
Had some time to kill and noticed none of the images on the page had alt tags.
=> Make Ember Users page accessible by adding alt tags

source/deprecations/v1.x.html.md
It's not much but at least it's something. Maybe someone with better writing skills should improve upon this.
Addresses: #2261
=> Add deprecation guide for ContainerView and CollectionView

data/users.yml
ops the url was wrong. sorry about that! :-)
=> fix coders51 wrong url

source/deprecations/v1.x.html.md
=> `bind-attr` deprecation

source/blog/2015-08-13-ember-2-0-released.md
[Rendered](https://github.com/mixonic/website/blob/blog-2.0/source/blog/2015-08-12-ember-2-0-released.md)
=> 2.0 blog post

data/meetups.yml
- Update meetup url
- Update Cincinnati organizers
=> Update Cincinnati meetup

data/users.yml
I've shut Crashlog down. Removing it.
=> Removed CrashLog.io - shutdown.

source/deprecations/v1.x.html.md
Based on feedback in #2320. Please do not merge yet, I'm waiting to hear back from @mixonic on another item.
=> [WIP] Small tweaks to the bind-attr deprecation details based on feedback.

source/blog/2015-09-02-ember-guides-status-update.md
[Rendered](https://github.com/michaelrkn/website/blob/0523a9fe9e1c599f684e0ab670f4d007d1c2b903/source/blog/2015-09-02-ember-guides-status-update.md)
=> Blog post on Guides status

source/deprecations/v1.x.html.md
Addresses the points concerning helpers in #2256.
I am still working on it, but feedback is welcome.
=> Add guide for helper methods deprecations

source/blog/2015-06-18-ember-data-1-13-released.md
Credit to @HeroicEric for reporting the issue.
=> Remove reference to non existent backgroundReload option

source/deprecations/v1.x.html.md
=> Add deprecation for positionalParams specification

data/team.yml, source/stylesheets/site.css.scss, source/team.html.erb
I've implemented the Team page redesign started by @max. Here's a preview:
cc @wifelette
=> Core Team page redesign

data/meetups.yml
=> Add Santiago, Chile meetup.

source/javascripts/app/examples/components/components/gravatar-image.js
Per https://twitter.com/photomatt/status/661053217535492096
=> Normalize email before md5

source/blog/2014-03-18-the-road-to-ember-data-1-0.md
Fixes the double word 'the the'.
=> Fix double word 'the' [ci skip]

source/deprecations/v2.x.html.md
=> Fixed a misnaming of the getowner polyfill

source/blog/2015-11-16-ember-2-2-released.md
[Rendered](https://github.com/mixonic/website/blob/2.2-blog/source/blog/2015-11-15-ember-2-2-released.md)
TODO:
=> 2.2 Blog Post

source/blog/2015-11-17-ember-data-2-2-released.md, source/javascripts/app/builds/app.js
=> Ember data 2 2 blog

source/deprecations/v1.x.html.md
Part of Issue https://github.com/emberjs/website/issues/2256
=> Add 1.13.2 Deprecations to Deprecations Guide

source/blog/2015-11-17-ember-data-2-2-released.md
=> Fix blog post reference to Ember instead of ED

source/deprecations/v1.x.html.md
Should complete fixes for https://github.com/emberjs/website/issues/2256
=> document remaining deprecations for 1.13.0 and 1.13.1

source/blog/2016-01-12-ember-data-2-3-released.md
=> Fix ED 2.4-beta.1 blogpost ds-references example typo

source/blog/2016-01-15-ember-2-3-released.md
[Rendered](https://github.com/mixonic/website/blob/2.3-blog/source/blog/2016-01-15-ember-2-3-released.md)
=> Ember 2.3 blog post

source/blog/2016-03-04-2016-ember-community-survey.html.md
=> Fixed spelling mistake in the community survey blog post

source/deprecations/v1.x.html.md
Fixes https://github.com/emberjs/website/issues/2492
=> Fixing a bad instance initializer link

source/_survey-reminder.html.erb
@acorncom pointed out a typo on the guides survey reminder that was also on website. Thanks @acorncom!
=> Fix typo in survey reminder header

source/about.html.erb
=> Fixes incorrect relative path if viewed at /about instead of /

lib/api_docs.rb, source/layouts/api.erb
=> Revert "Hide private and deprecated classes and namespaces from sidebar."

Rakefile, source/layouts/guide.erb
I have updated the root SSL certs (I'm still on Mavericks) via both system update and RVM's `rvm osx-ssl-certs update all`, but neither helped.
This works, but feels odd....
=> Use github raw instead of guides.emberjs.com because my system sucks.

source/deprecations/v2.x.html.md
Addresses the legacy addon part of #2538
=> Add section on deprecating legacy support addons

source/deprecations/v2.x.html.md
See https://github.com/emberjs/ember.js/pull/12983
=> Add `Ember.Backburner` to deprecation guide

data/team.yml
=> Fix path to image for pangratz

source/legal.html.erb, source/stylesheets/components/legal.css.scss, source/stylesheets/site.css.scss
See http://quick.as/kw7u56y1. Sorry, I don't know how to do @ryanlabouve's fancy gifs :D
=> Makes legal page responsive

source/security/index.md, source/stylesheets/components/security.css.scss, source/stylesheets/site.css.scss
Same drill as legal, basically. So far:
* security
* guidelines
=> Makes pages responsive

source/sponsors.html.erb, source/stylesheets/components/sponsors.css.scss, source/stylesheets/site.css.scss
=> Makes sponsors page responsive

source/blog/2016-01-12-ember-data-2-3-released.md, source/blog/2016-03-13-ember-data-2-4-released.md
This updates the code samples in the blog post, which are misleading.
This addresses emberjs/data#4355.
@adam-knights what are your thoughts here?
=> Clarify usage of `id()` and `ids()` for references

source/deprecations/v2.x.html.md
Addresses issue [#13243](https://github.com/emberjs/ember.js/issues/13243) and goes along with PR [#13424](https://github.com/emberjs/ember.js/pull/13424).
=> Deprecate Ember.Binding

source/about.html.erb, source/stylesheets/about.css.scss
This fixes PR #2562 for @rwjblue 's nitpick about getting the version from the json file.
=> Improves the call to action in the frontpage

README.md
=> Add link for cloning using HTTPS

source/stylesheets/_variables.scss, source/stylesheets/about.css.scss, source/stylesheets/blog.css.scss, source/stylesheets/builds.css.scss, source/stylesheets/colors.css.scss, source/stylesheets/examples.css.scss, source/stylesheets/guides.css.scss, source/stylesheets/highlight.css.scss, source/stylesheets/shared.css.scss, source/stylesheets/site.css.scss
The original PR was made at the EmberConf Contributors Workshop. I've extracted these few commits (plus rebased onto master, of course), to be able to review & merge them in independently from other changes, such as the responsive stuff, etc.
=> Minor CSS enhancements

source/stylesheets/_variables.scss, source/stylesheets/about.css.scss, source/stylesheets/blog.css.scss, source/stylesheets/builds.css.scss, source/stylesheets/colors.css.scss, source/stylesheets/dashboard.css.scss, source/stylesheets/examples.css.scss, source/stylesheets/guides.css.scss, source/stylesheets/highlight.css.scss, source/stylesheets/shared.css.scss, source/stylesheets/site.css.scss, source/stylesheets/survey.css.scss
Includes `@import "variables";` statements to fix `middleman build`, otherwise the same as #2603
=> Minor css enhancements reloaded

.travis/deploy.sh
More details on this can be found here: https://github.com/emberjs/website/pull/2603#issuecomment-221954665
=> Fix travis builds so PR branches can have builds turned on again

source/blog/2016-06-09-ember-data-2-6-released.md
Matches the revisions that got made so that Ember Data releases are categorized separately from Ember releases on our sidebar ...
=> Updated tag for Ember Data info

source/learn.html.erb
This is a PR for one of the tasks listed in #2611.
=> Ecosystem section

source/learn.html.erb, source/stylesheets/learn.css.scss, source/stylesheets/site.css.scss
Started drafting learn page. KISS for now.
- Glossary
- Ember Inspector
- Ember user
- Newbie (no MVC or JS experience)
- From Rails (MVC experience; no JS experience)
- From BackBone (MV* experience, kinda; JS experience)
- Ember addon developer
- "regular" addon
- CLI addon
- engine
- Contributor
- Documentation
- Code
=> [WIP] Learn page

source/deprecations/v2.x.html.md
See https://github.com/emberjs/website/pull/2600#discussion_r71019852
=> Fixes arr.contains typo

source/blog/2016-07-25-ember-data-2-7-released.md
=> Publish the Ember Data 2.7 release blog post

source/deprecations/v2.x.html.md
=> Added ember-handlebars-safestring to Deprecated in 2.8.

data/users.yml
Wrong logo file name in users.yml
=> Rename splitty image name

source/blog/2016-04-28-baseURL.md
Closes https://github.com/ember-cli/ember-cli/issues/6212
=> Clarify baseURL blog post.

source/blog/2016-09-07-ember-node-lts-support.md
Current state is ready for review in advance of landing. I'm speaking for the decisions made on the Ember CLI team which primarily lives in the Node.js ecosystem and extrapolating.
/cc @mixonic @ErisDS
/cc Ember CLI @chadhietala @kategengler @kellyselden @rwjblue @stefanpenner @trabus @Turbo87
=> Ember Node.js LTS Support

source/blog/2016-09-08-ember-2-8-and-2-9-beta-released.md
=> Link to Enumerable#includes polyfill in 2.8 blog post.

source/community/meetups.html.erb, source/stylesheets/components/meetups.css.scss, source/stylesheets/site.css.scss
=> Make meetups page responsive

source/blog/2016-10-17-ember-2-9-released.md
=> Grammatical fixes

source/deprecations/v1.x.html.md
Fix for #2615, incorporating feedback in #2631
=> Fix solution for Modifying a Property within `didInsertElement`; walkthrough scenarios

source/security/index.md
=> Fix RFPolicy link

config.rb
=> [BUGFIX] Builds sub-routes

source/blog/2016-11-30-ember-2-10-released.md
=> Update 2.10 release post now that CLI beta is published.

source/deprecations/ember-data/v2.x.html.md
As part of https://github.com/emberjs/data/issues/4695.
=> Add deprecation for using the global version of DS

source/learn.html.erb
=> [WIP] Adds a FAQ section to the learn page

source/learn.html.erb
Would be nice to be able to link directly FAQs and items in the FAQs.
=> Add ids on FAQ section

source/deprecations/ember-data/v2.x.html.md
This adds a feature label to the deprecations that are for pending
features so they can be more easily identified.
=> Add feature labels to pending deprecations

source/ember-users.html.erb
=> Implements srcset for ember user images with x2 file

source/ember-users.html.erb, source/stylesheets/pages/ember-users.css.scss, source/stylesheets/site.css.scss
It's my attempt at doing a slight modernisation.
Preview: https://deploy-preview-2783--chess-master-boris-50065.netlify.com/ember-users/
=> Updates ember-users style

data/dashboard.yml
=> Add data for some recent Ember.js RFCs

source/internal_api/class.html.erb, source/internal_api/module.html.erb, source/layout.erb
=> Add robots noindex meta tag for internal_api

source/ember-community-survey-2016.html.erb
- less confusing to use percentages, since they are used elsewhere and reader doesn't have to do math
- fixed grammar
=> Fixed wording for the 2016 community survey

data/dashboard.yml, source/dashboard.html.erb, source/stylesheets/dashboard.css.scss
This adds the cards format for RFC features, and groups features by release status (RFC, canary, beta, released)
=> Add feature "cards"

data/dashboard.yml, source/dashboard.html.erb, source/stylesheets/dashboard.css.scss
Fixes https://github.com/emberjs/rfcs/issues/103
Prior discussion: https://github.com/emberjs/website/pull/2393
* Manually updated yaml file with basic info about RFCs
* List ordered by "stage"
* Add more info to RFC listing, like precedence, etc
* Try to automate parts of the process
=> Updates dashboard

source/about.html.erb, source/stylesheets/about.css.scss, source/stylesheets/site.css.scss
=> Responsive-fy the website

source/about.html.erb, source/stylesheets/about.css.scss, source/stylesheets/components/ember-button.css.scss, source/stylesheets/site.css.scss
home(about) page style updates to better support rwd
=> CSS updates

source/dashboard.html.erb, source/javascripts/dashboard.js
Uses the same technique as /builds.
Preview: https://deploy-preview-2820--chess-master-boris-50065.netlify.com/dashboard/
=> Make /dashboard an Ember app

README.md
=> Update build/release section of the README

static.json
With the PR at https://github.com/heroku/heroku-buildpack-static/pull/65 this now works.  Thanks very much @hone !
=> Redirect all http traffic to https

source/stylesheets/_header.scss
- increased navbar font size
- increased size of header navbar (by 20px)
- put padding on link instead of li element (to increase clickable area)
- consolidated some of the code
=> increase font size

source/layouts/blog.erb
Fixes https://github.com/emberjs/website/issues/2880
=> Permit HTTPS for comments

source/ember-community-survey-2017.html.erb
=> Fix typo in *New Release Adoption*

source/stylesheets/_variables.scss
- added variables for css breakpoints to help transition design work
=> css breakpoints

source/learn.html.erb
This was a question at the Boston meetup Core Team panel, thought it might make a good addition.
=> [WIP] Add second FAQ question

source/stylesheets/site.css.scss
Addresses https://github.com/emberjs/website/issues/2918
cc @locks
=> Add padding to ember users in grid

config.rb
These files are extracted as https://github.com/ember-learn/builds by https://github.com/emberjs/website/pull/2720
=> Remove unnecessary `ignore` section

config.rb
The files to be ignored ware gone by https://github.com/emberjs/website/commit/2b192878e77816d8274a2179e00aa4c9e7ca4c98
=> Remove `ignore` option from `minify_javascript`

source/layout.erb
Fixes https://github.com/emberjs/website/issues/2932.
=> Adds custom element shim

source/deprecations/v2.x.html.md
part of https://github.com/emberjs/website/pull/2914#issuecomment-311255869
**before:**
**after:**
/cc @locks
=> fix `Ember.MODEL_FACTORY_INJECTIONS` deprecation headings

source/deprecations/v2.x.html.md
part of https://github.com/emberjs/website/pull/2914#issuecomment-311255869
closes https://github.com/emberjs/website/issues/2931
=> add custom event manager deprecation

source/about.html.erb, source/stylesheets/about.css.scss, source/stylesheets/components/call-to-action.css.scss
- CTA occupies full-width on < tablets
- Command line commands are not shown for < tables
- Tweaks box shadows
=> Slightly re-styles CTA for responsiveness

source/blog/2017-08-14-ember-2-15-released.md
First pass at Ember CLI section for 2.15.0
=> Ember CLI Changes

source/logos.html.erb
Fix for https://github.com/emberjs/website/issues/2982 
cc @wifelette @jenweber  :)
=> adding pms color info to logos page

data/meetups.yml
Melanie has been the organizer of this meetup for a while. Updated to reflect current leadership.
=> Update Chicago Ember.js Meetup Organizer

README.md
Fixes https://github.com/emberjs/website/pull/2998
=> Update info on API docs

source/logos.html.erb
Preview https://ember-website-pr-2999.herokuapp.com/logos/
=> Cheeky tweak to color the hex value with the actual color

source/deprecations/v2.x.html.md
=> fixes formatting bug on deprecations page

data/users.yml
=> added inactive field for a few users

source/blog/2017-10-10-glimmer-progress-report.md
Waiting for review from the core team on this one.
=> October Glimmer Progress Report

source/stylesheets/about.css.scss, source/stylesheets/base/_grid-settings.scss, source/stylesheets/base/_typography.scss, source/stylesheets/base/_variables.scss
Removed duplicated rules and delete unnecessary comments.
=> Remove duplicate rules from stylesheets #3029

source/stylesheets/base/_base.scss, source/stylesheets/components/legal.css.scss, source/stylesheets/site.css.scss
Some imports were requiring files which are in the same directory. I have also removed the call for `@import: base/variables` as this is already being referenced in `base` which already imports `_variables`.
Finally nested the media query within `#legal-wrapper` to save some lines and increase readability :)
Cheers guys,
=> Some style tweaks and tidying

source/stylesheets/site.css.scss
Updated font-family on body element to use $base-font-family variable for better consistency.
=> Update font-family value

source/layout.erb
Helps establish ownership for Google Webmaster tools
=> Added in verification for Google Webmaster tools

source/deprecations/ember-cli/v2.x.html.md, source/deprecations/ember-data/v2.x.html.md, source/deprecations/index.html.md, source/deprecations/v1.x.html.md, source/deprecations/v2.x.html.md, source/stylesheets/pages/deprecations.css.scss, source/stylesheets/site.css.scss
=> Responsify /deprecations pages

source/deprecations/v2.x.html.md
=> Remove duplicated code in deprecation guide

source/learn.html.erb
- added sections
- only should have one h1 per page- changed the others to h2
=> Update to learn html

source/learn.html.erb
Issue #3058: Learn page needs semantic HTML update
=> replaced h2 tags with h3

source/stylesheets/base/_typography.scss
- removed the h1 from the group of headings that contained text-transform: capitalize since it doesn't fit well for the H1s on the website (because it capitalizes Ember.Js)
- (sorted the properties for the h1 css to make it neater)
=> Updated some of the typography for the H1

source/stylesheets/components/call-to-action.css.scss
=> Fix sass variable name typo

source/deprecations/v2.x.html.md
Fixes https://github.com/emberjs/ember.js/issues/15805 😉
=> Fixes broken links on Enumerable#contains deprecation

source/stylesheets/site.css.scss
https://github.com/emberjs/website/issues/2957
=> Change background color for sponsors

source/blog/index.html.erb, source/blog/tag.html.erb, source/layouts/blog.erb, source/stylesheets/pages/blog.css.scss
First-time contributor.
Addresses #3049
=> Feature: Indicate guest or syndicated blog post

source/stylesheets/about.css.scss, source/stylesheets/base/_typography.scss, source/stylesheets/base/_variables.scss, source/stylesheets/builds.css.scss, source/stylesheets/components/call-to-action.css.scss, source/stylesheets/components/ember-button.css.scss, source/stylesheets/components/footer.css.scss, source/stylesheets/examples.css.scss, source/stylesheets/guides.css.scss, source/stylesheets/pages/about.css.scss, source/stylesheets/pages/blog.css.scss, source/stylesheets/pages/community.css.scss, source/stylesheets/pages/meetups.css.scss, source/stylesheets/pages/tomster-commission.css.scss, source/stylesheets/shared.css.scss, source/stylesheets/site.css.scss, source/stylesheets/survey.css.scss, source/stylesheets/vendor/_docsearch-variables.scss, source/stylesheets/vendor/_docsearch.scss
- tried to eliminate some of the extra top margins/padding on pages
- replaced more colors with appropriate variables (i.e., white was replaced with $white) 
- removed $orange-color (replaced instances with $orange or $orange-darker, where appropriate) 
- removed $ember-orange (replaced with $orange) 
- updated the value for white (fff  to fdfdfd)
- updated the value for black (000 to 212121)
---------
=> CSS Cleanup

source/blog/index.html.erb, source/stylesheets/pages/blog.css.scss
Screenshot of change: 
- put date on line below with a different color and smaller font size. 
- increase font size for author credit.
=> Update to blog style

data/meetups.yml
This updates the Ember Columbus organizer list to match [our Ember Columbus Meetup page](https://www.meetup.com/ember-columbus/)
=> Update Ember Columbus organizers

source/about.html.erb
I'm not sure if this is the URL that this is supposed to go but I think this is better than not going anywhere 😄 
LMK if this should point elsewhere.
=> Add missing href for Ember Conf CTA

source/blog/2017-11-20-ember-2-17-released.md
- [Rendered](https://github.com/emberjs/website/blob/2-17-release-blog-post/source/blog/2017-11-20-ember-2-17-released.md)
- Preview
- Ember
- Ember Data
- Ember CLI
=> Ember 2.17 Release Blog Post

source/stylesheets/base/_variables.scss
- changed background color to $white
- added status colors
- added standardized gray shades
- grouped colors for deprecation (including browns)
Screenshot of colors:
=> updating CSS variables to prep for CSS cleanup

source/blog/2017-01-23-ember-2-11-released.md, source/blog/2017-04-29-ember-2-13-released.md, source/blog/2017-09-01-ember-2-15-released.md, source/blog/2017-11-20-ember-2-17-released.md
=> Add/update LTS info

data/users.yml
Several companies have been acquired or changed names. This PR updates the URLs and names, but not any of the logos.
=> Update User Company Name Changes from Acquisition or Name Changes

source/stylesheets/about.css.scss, source/stylesheets/base/_structure.scss
- decreased the min-height on the .main  (it was too big)
- decreased the top margin on the home page, as it's no longer needed since the page layout updates.
=> vertical height tweaks

source/layout.erb
-added back in the 300 font size for ssp
=> layout update

source/community.html.erb, source/stylesheets/base/_typography.scss, source/stylesheets/blog.css.scss, source/stylesheets/pages/blog.css.scss
A few minor changes to the heading styles based on team & designer feedback.
=> a few minor changes to the typography design

data/users.yml
The list of users has many companies with broken links or have been shut down. I went through the whole list and checked all users. This PR marks the `inactive` ones I found.
=> Mark Broken Links and Shutdown Companies as "inactive"

source/learn.html.erb
=> Wrap list items in ul element

source/community.html.erb
I made some changes to https://emberjs.com/community/ to create a newsletter section. Here's what it looks like:
Partially addresses some ideas in #3129
=> create a newsletters section for Ember Blog, Weekly, Times #3129

source/tomster/faq.html.erb
Solves: https://github.com/emberjs/website/issues/3140
Hi @MelSumner - I was looking for a good first issue, and used https://github.com/emberjs/website/issues/3140 to set up the repo with Docker. Let me know what you think. (I'm @amyrlam on Ember Slack as well!)
IS:
WAS:
=> Correct link

source/_header.html.erb
- Remove LTS from navbar until it is implemented
=> Navbar tweaks

source/stylesheets/pages/tomster-commission.css.scss
- increased input field width from 70 to 100% to fill the column width
- made the radio buttons inline-blocks so the label was on the same line
- added a little extra margin to the top of the labels to give clearer separation
=> style tweaks on form

source/deprecations/v2.x.html.md
Fixes: emberjs/ember-2-legacy#38
cc @locks
=> Add documentation about ember-2-legacy addon

source/community.html.erb
Fixing another broken link found by SEO crawling
=> Fixing broken link

static.json
Seeks to address https://github.com/ember-learn/ember-api-docs/issues/427
=> Adjust proxy settings for api to better work with fastboot

config.rb
Companion PR to @MelSumner's #3188. There isn't a reason for any page to be not responsive any more!
=> Make all pages responsive by default

source/blog/2018-02-16-ember-3-1-beta-released.md
=> Adjust `npm test` section in Ember 3.1 release blog post

source/deprecations/v2.x.html.md
Complements https://github.com/emberjs/ember.js/pull/14590.
=> Add upcoming deprecations

source/blog/2016-01-12-ember-data-2-3-released.md, source/blog/2016-01-14-security-releases-ember-1-11-4-1-12-2-1-13-12-2-0-3-2-1-2-2-2-1.md, source/blog/2016-01-15-ember-2-3-released.md, source/blog/2016-01-23-core-team-face-to-face-january-2016.md, source/blog/2016-02-25-announcing-embers-first-lts.md, source/blog/2016-02-29-ember-2-4-released.md, source/blog/2016-03-04-2016-ember-community-survey.html.md, source/blog/2016-03-13-ember-data-2-4-released.md, source/blog/2016-03-23-introducing-zoey.md, source/blog/2016-04-11-ember-2-5-released.md, source/blog/2016-04-28-baseURL.md, source/blog/2016-05-03-ember-data-2-5-released.md, source/blog/2018-02-21-2018-ember-community-survey.html.md, source/stylesheets/pages/404.css.scss, source/stylesheets/pages/brand.css.scss
- added 'responsive: true' to more blog posts (including the most current) so they are device-agnostic
- updated some of the page .scss files to include the base file import that they were missing. 
(will do the button component updates in a different PR)
=> blog posts. again.

source/blog/2018-02-21-2018-ember-community-survey.html.md, source/ember-community-survey-2018.html.erb, source/stylesheets/_survey-reminder.css.scss, source/stylesheets/about.css.scss, source/stylesheets/base/_structure.scss, source/stylesheets/blog.css.scss, source/stylesheets/components/buttons.css.scss, source/stylesheets/components/ember-button.css.scss, source/stylesheets/site.css.scss, source/stylesheets/survey.css.scss
- made the max page width consistent with other elements
- made the buttons consistent on the blog and survey page
- fixed the a11y of the button with the image
- put a tinge of color on the body background- the white is just toooooo stark. 
- made the background of the survey reminder the same accent blue used for the "jobs" image and the post author names (we can ditch this if @mixonic doesn't like it)
Screenshot of using the blue on the survey banner:
=> some style updates

source/deprecations/v3.x.html.md
Deprecation message for https://github.com/emberjs/ember.js/pull/16270
=> Add direct cp assignment deprecation

source/_survey-reminder.html.erb, source/ember-community-survey-2018.html.erb, source/layout.erb
@mixonic & @akankshadharkar 
To be merged once the survey closes.
=> remove 2018 survey CTA

README.md
If this looks good, I'll add a similar section to our other apps.
=> add links to other repos and instructions for new contributors

source/_survey-reminder.html.erb, source/layout.erb
Temporary, will remove after a day or two
=> Add a CTA for the survey results

data/team.yml
=> adding team to Mel

source/community.html.erb, source/stylesheets/pages/community.css.scss
Before: https://cl.ly/0J3B363R1b1I
After: https://cl.ly/313z1f0l0D0I
=> Move video to the bottom of the community page #3218

source/stylesheets/pages/about.css.scss
addresses https://github.com/emberjs/website/issues/3225
=> centers productivity features

source/about.html.erb
=> Remove EmberConf callout #3229

source/_survey-reminder.html.erb, source/layout.erb
Drop the callout for survey results from the header. It has been about a week.
=> Drop the survey results promo

source/stylesheets/about.css.scss
turned this back on for mobile now that EmberConf is over and it's not conflicting with the survey banner. Resolves #3205
=> turning job board banner back on for mobile

source/learn.html.erb
Resolves #3246 
I added some things... For convenience of review:
Glimmer is a rendering engine used in Ember. However, in order to build Ember apps, you don't need to know anything about Glimmer, other than it's super fast and that the contributors to the core codebase love to geek out about it. It's all behind the scenes. If you're curious to know how the Glimmer project fits into the roadmap for Ember's development, you can learn more here.
Here are some strategies that may help you out. (link to reader questions)
Yes. Controllers are the right place to put URL query params, actions and attributes that need to be passed from the route level to components, and lifecycle hook code.
Ember.js has a strong emphasis on developer productivity, which means that framework developers take great …
=> rewrite learning page FAQ #3246

data/team.yml
added the twitter handles that were missing for the team page.
=> updating the Twitter info for everyone for issue #3135

data/meetups.yml
Updating Boston meetup info to the active meetup and organizers (who have been leading the meetup for 5+ months already).
=> Updating boston meetup info

source/stylesheets/pages/teams.css.scss, source/stylesheets/shared.css.scss, source/team.html.erb
- @sivakumar-kailasam can you check the deploy to see if this resolves the mobile issue you observed
- need to still cross-browser check this PR to make sure it's okay in IE
=> resolved issue where things were too scrunched on mobile devices

source/stylesheets/base/_typography.scss
Removed some duplicate code in the h2 styles so the intended margins render correctly. 
(@jenweber if you still want to change the actual number amount that's fine)
=> updating h2

source/stylesheets/base/_structure.scss
-made the container class on tablet sizes a bit wider to better accommodate the search box
=> updated .container width

data/meetups.yml
=> remove Pittsburgh meetup

source/learn.html.erb
Closes #3274 
I was wrong earlier when I thought that upgrading the CLI shows you new deprecations. Oops. I was actually thinking of an addon that does that. At @locks request, I have corrected that mistake and also gave a stronger message around "future proofing" an app.
cc @MelSumner just so I don't perpetuate the misunderstanding.
=> Deprecations and faq update

data/meetups.yml
Updated to reflect: https://www.meetup.com/Chicago-Ember-js/
=> add Sean Massa as Chicago meetup organizer

source/stylesheets/_footer.scss
When mousing over the footer icons there is an underline. This PR fixes that.
=> Fix footer mouseover

source/blog/2018-04-01-the-emberjs-times-issue-43.md, source/stylesheets/pages/blog.css.scss
=> WIP: Release Ember.js Times - Issue #43

source/blog/2018-04-22-ember-learning-update.md
Posting an update on the March F2F to share with the community.
=> Learning team update blog post

source/blog/2018-04-01-the-emberjs-times-issue-44.md
Adds Ember CLI details for Issue No. 44
=> blog(embertimes): add ember-cli section

source/blog/2018-04-27-the-emberjs-times-issue-44.md
=> Correct date in file name and alias

source/layout.erb, source/stylesheets/base/_typography.scss, source/stylesheets/site.css.scss
Relates To: https://github.com/emberjs/website/issues/3137
Hover:
Focused:
=> Add a link to contribute on the bottom of all pages

source/blog/2018-05-02-ember-2018-roadmap-call-for-posts.md
h/t @MelSumner @wifelette 
Waiting on post links from @ryanto, ~@mixonic~, @MelSumner
=> Add blog post calling for blog posts

source/blog/2018-05-11-the-emberjs-times-issue-46.md
Made some minor edits @Gaurav0 @kennethlarsen @jessica-jordan 
I think we use sentence case for headers?
=> Ember times update

source/blog/2018-05-11-the-emberjs-times-issue-46.md
[Rendered](https://github.com/jessica-jordan/website/blob/61d40c71b13bbf507b44d70ef1532b8ea5006766/source/blog/2018-05-11-the-emberjs-times-issue-46.md)
=> blog(embertimes): add readers q, intro for issue 46

source/blog/2018-05-11-the-emberjs-times-issue-46.md
To be released on Friday, May 11th.
This week's topics include:
- Jen's & Chris' May Stackoverflow live stream + updated twitch link. See also https://github.com/emberjs/website/pull/3329
-  Guides App Release upcoming + CTA to test the site (https://emberguides.stonecircle.io/release/) and open issues at https://github.com/ember-learn/guides-app/issues
....and more to be added during the week
Please also add further topics to the comments below or mention any that you find interesting at [#topic-embertimes](https://embercommunity.slack.com/archives/C8P6UPWNN/p1525448225000074)
=> WIP: Release Ember.js Times Issue #46

source/blog/2018-05-18-the-emberjs-times-issue-47.md
Part of Ember.js Times issue No. 47 - #3339
=> blog(embertimes#47): add section on template-recast

source/blog/2018-05-18-the-emberjs-times-issue-47.md
This adds some more formatting, as well as the intro / readers' questions section to the upcoming Ember Times issue.
=>  Ember.js Times#47: Contributors' Section, Intro, Readers Q Recap and Formatting

source/team.html.erb
@MelSumner 
With this PR, we are completing [#3288](https://github.com/emberjs/website/issues/3288)
=> [3288] Update team mission

source/blog/2018-05-25-the-emberjs-times-issue-48.md
Contribution to the emberjs-times#48
=> Add AddonDocs section

source/blog/2018-06-01-the-emberjs-times-issue-49.md
Adds the content to https://github.com/emberjs/website/pull/3374
=> trying to add the content from the blog

source/blog/2018-06-01-the-emberjs-times-issue-49.md, source/stylesheets/pages/blog.css.scss
To be released on June 1st, 2018.
Special Edition featuring @mansona and a look into the Guides app & its internals.
Feel free to add further topics to the comments below or mention any that you find interesting at #topic-embertimes
Once this is merged, we should also merge #3377 to highlight this post as the only recent Ember Times post.
=> Release Ember.js Times Issue #49

source/sponsors.html.erb, source/stylesheets/pages/sponsors.css.scss
Updates the copy and the layout for the sponsors page
Closes #3376 #3378
=> Issue: Update sponsors page copy and layout

source/blog/2018-06-08-the-emberjs-times-issue-50.md
=> contributing to the blog

source/blog/2018-06-08-the-emberjs-times-issue-50.md
This adds more content for the Ember.js Times Edition #50, including the introduction, a status update on the packager feature in ember-cli and the list of contributors.
I can add the outstanding Readers' Question in another follow-up, once I have the answer and the url to the discussion board ready.
Related to #3373
=> Ember.js Times#50: Adds Intro, Ember CLI section, Contributor's Section

source/blog/2018-06-01-the-emberjs-times-issue-49.md
This removes the Issue No. 49 from the list of recent posts, as we'd like to only keep the most recent Ember Times edition up in the Recent Posts category.
Should be merged after #3373
=> blog(embertimes#49): Remove Ember Times #49 from list of recent posts

data/team.yml
I don't know if this would actually make a difference but I noticed it when I was taking a look at the data
this is the only entry that has "Last" with a capital letter 👍
=> fixing capitalisation

source/about.html.erb
This removes duplicated content in the homepage
Closes #3399
=> Removed duplicated content (#3399)

source/blog/2018-06-15-the-emberjs-times-issue-51.md
Adds a section for Ember Twiddle's new release.
N/A
N/A
=> Add section for Ember Twiddle

source/blog/2018-06-08-the-emberjs-times-issue-50.md
With #3396 released, we can now remove edition 50 from the list of recent posts.
Related to #3396
=> Blog(embertimes#50): remove post from recent posts

source/about.html.erb
This fix the "Who's using Ember" section in homepage. I don't know if it's exactly like it was before it broke, but i think that bringing back those section into the parent container should fix it.
Closes #3392
=> Homepage "Who's using Ember" slider fix (#3392)

source/blog/2018-06-15-the-emberjs-times-issue-51.md
This removes the second to latest edition of the newsletter from the list of recent posts. This should be merged after https://github.com/emberjs/website/pull/3414
=> WIP: blog(embertimes#51): remove ember times 51 from recent posts

data/users.yml, source/layout.erb
This PR adds a script that allows our partners at Fastly to test a new analytics project on the website, as per their request and at no cost to us. More information about the project by visiting the project's open source repo: https://github.com/fastly/insights.js.
=> adds Fastly insight script

source/blog/2018-06-29-the-ember-times-issue-53.md
[Rendered](https://github.com/emberjs/website/pull/3425/files)
=> Added section on SSD vs RAM Disk building

source/blog/2018-06-22-the-ember-times-issue-52.md
This removes the second to latest edition of the Ember Times from the list of `Recent Posts`, now that Issue No. 53 is out.
Related to #3423
=> blog(embertimes): remove issue#52 from list of recent posts

source/blog/2018-07-02-ember-3-2-released.md
- updated the date to 7/2
- added alias for previous date
- added a note about lack of prose for 3.3 beta
- added a note about the post being later than expected
=> updated blog date to more accurately reflect the appropriate date

source/blog/2018-07-06-the-ember-times-issue-54.md
This adds a short section about the Qunit Dom TypeScript update to the Ember Times Edition No. 54. 
This also adds some formatting to remove double plusses (+) in front of text lines.
https://github.com/emberjs/website/pull/3438
=> blog(embertimes#54): add section on qunit-dom

source/blog/2018-07-06-the-ember-times-issue-54.md
=> Added Section on Ember Twiddle release

source/blog/2018-07-06-the-ember-times-issue-54.md
This adds a section on the 3.2 release blog post.
Related to #3438
=> Ember Times#54: add section on release blog post

source/blog/2018-07-06-the-ember-times-issue-54.md
I did this in the browser UI as one commit (sorry) because I couldn't pull the branch? Copy edits were pretty minor though.
=> Add section and small copy edits

source/blog/2018-07-06-the-ember-times-issue-54.md
This adds the another contributor to the list of participants for his support on the devops side of things.
Relates to #3438
=> blog(embertimes#54): add head of oss devops to list of contrib.

source/blog/2018-07-13-the-ember-times-issue-55.md
This adds a short section about recent SEO efforts to the next Ember Times.
=> Ember Times No. 55 - Section about SEO

source/blog/1991-07-13-the-ember-times-issue-55.md
Let me know if you want any edits, or feel free to commit directly to the branch/file
=> Add blurb on RFC #345

source/blog/1991-07-13-the-ember-times-issue-55.md
Forgot to highlight a few keywords in my section and also added this week's contributors already ✨
=> blog(embertimes#55): add bold formatting and contributors

source/blog/1991-07-13-the-ember-times-issue-55.md
Adds how to create RFC section to ember times
=> Adds how to create RFC section to ember times

source/blog/2018-07-13-the-ember-times-issue-55.md
This updates the emoji in the header title for the ember cli update section and in the intro.
| before [see review app](https://ember-website-staging-pr-3452.herokuapp.com/blog/2018/07/13/the-ember-times-issue-55.html#toc_a-href-https-github-com-ember-cli-ember-cli-update-don-t-worry-ember-cli-got-you-covered-a) | after |
|--|--|
| <img width="845" alt="screen shot 2018-07-13 at 14 11 41" src="https://user-images.githubusercontent.com/8811742/42691308-c3434172-86a7-11e8-8b43-2c7963a19145.png">| <img width="862" alt="screen shot 2018-07-13 at 14 16 44" src="https://user-images.githubusercontent.com/8811742/42691319-cad178f0-86a7-11e8-95d4-f9135ec8cf40.png">|
=> blog(embertimes#55): fix emoji

source/blog/1991-07-13-the-ember-times-issue-55.md, source/blog/2018-07-13-the-ember-times-issue-55.md
=> [Ready for Publishing] Embertimes#55 

source/blog/2018-07-16-ember-3-3-released.md
- [Rendered](https://github.com/emberjs/website/blob/feature/3-3-blog/source/blog/2018-07-16-ember-3-3-released.md)
- Preview
- Ember
- Ember Data
- Ember CLI
=> [WIP] 3-3 blog post

source/blog/2018-07-20-the-ember-times-issue-56.md
First stab - may try to flesh out tmrw. Any feedback let me know!
I found it tough to say much about the podcast but could summarize the RFCs if needed. I also wasn't sure if it is indeed "splatributes"?
There is some double bracket curly syntax in here that may need to be removed also... will comment inline too.
=> Amy supershort writeup for Ember Times 56

source/blog/2018-07-20-the-ember-times-issue-56.md
TodoMVC Ember update - ember times section
=> TodoMVC Ember update - ember times section

source/blog/2018-07-20-the-ember-times-issue-56.md
This is a quick write up for the 3.3 release, adds the contributors and updates the urls to the blog / goodbits.
I also added a picture to the release post section, hope the 🎨 is appreciated! ✨
=> Ember Times 56: Add Release 3.3 Post Announcement + Contributors

source/blog/2018-07-20-the-ember-times-issue-56.md
This adds the intro section, authors, and some more minor edits
=> Embertimes No 56: Intro + some more edits

source/blog/2018-07-20-the-ember-times-issue-56.md
Copied over the ideas section here -Amy
=> [Editing - WIP] ember-times-56

source/blog/2018-07-27-the-ember-times-issue-57.md
This adds a short section about the ember-data live stream managed by @runspired
=> blog(embertimes#57): add ember-data live stream section

source/blog/2018-07-27-the-ember-times-issue-57.md
Just adding an inspector post for the times 😄
=> Add inspector post

source/blog/2018-07-27-the-ember-times-issue-57.md
copy edits
- Some spacing seemed off
- Standardizing section headings to be sentence case (for the most part)
- We tend to use Ember Data and ember-data for repos, should we be consistent?
Add short writeup on https://medium.com/@lukedeniston/ember-webassembly-just-got-way-easier-1e4ec6ca40ab
=> Amy ember times # 57 update

source/blog/2018-07-20-the-ember-times-issue-56.md, source/blog/2018-07-27-the-ember-times-issue-57.md
=> Ember Times No. 57: Add Contributors And Readers' Question Intro

source/blog/CONTRIBUTING.md
- Creates contributing.md for ember times
=> Creates contributing.md for ember times

source/blog/2018-08-03-the-ember-times-issue-58.md
=> Add section about homepage survey

source/blog/2018-08-03-the-ember-times-issue-58.md
Update some blog text to be neutral. I understand that the phrasing was meant as a joke/play on words, but I associate this phrase with causing a lot of harm to a lot of people.
=> Ember times - Update wording on CLI guides project

source/blog/2018-08-10-the-ember-times-issue-59.md
How Esteban used Ember to create Chrome Extensions by combining multiple addons from around the community.
Summarizes the blog post for The Ember Times
A Framework for Ambitious Chrome Extensions: https://envoy.engineering/a-framework-for-ambitious-chrome-extensions-b08d1f4b944d
=> blog(embertimes59): A Framework for Ambitious Chrome Extensions

source/blog/2018-08-10-the-ember-times-issue-59.md
This adds a short writeup on the Component Bounds RFC: https://github.com/emberjs/rfcs/pull/351
=> blog(embertimes#59): add Component Bounds RFC writeup

source/blog/embertimes-template.md
Follow-on to https://github.com/emberjs/website/pull/3498 to make the template easier to update / less prone to error.
=> Update Ember Times template

source/blog/2018-08-10-the-ember-times-issue-59.md
=> Add outdoorsy to ember times

source/blog/2018-08-10-the-ember-times-issue-59.md
BTW did we remove this section?
The Ember Times is What We Make It 🙌
The Ember Times is a weekly news editorial featuring all the new things that are going on in Emberland. Subscribe to our e-mail newsletter to get the next edition right to your inbox. And if you've always wanted to be an OSS journalist yourself, drop by #topic-embertimes on the Ember Community Slack Chat and write the next edition of the Ember Times together with us!
=> Fixed Broken Link + Added Emojis

source/blog/2018-08-17-the-ember-times-issue-60.md
Adds ember-cli-create section to ember times
=> adds ember-cli-create section to ember times

source/blog/2018-08-17-the-ember-times-issue-60.md
For https://github.com/emberjs/website/pull/3503
=> Amy writeup for Ember Times #60

source/blog/2018-08-17-the-ember-times-issue-60.md
This adds the contributors' section, a few formatting edits and the section about the Discord RFC FCP
=> For EmberTimes#60: Contributors + Discord RFC FCP

source/blog/2018-08-17-the-ember-times-issue-60.md
=> For EmberTImes#60: Add Readers' Question

source/blog/2018-08-17-the-ember-times-issue-60.md
=> For EmberTimes#60: Add Intro + more Formatting

source/blog/2018-08-17-the-ember-times-issue-60.md
=> Ember Times Issue 60

source/blog/2018-08-10-the-ember-times-issue-59.md
This removes No. 59 from the list of recent posts now that [issue 60 is already out](https://www.emberjs.com/blog/2018/08/17/the-ember-times-issue-60.html).
=> blog(embertimes): remove issue 59 from list of recent posts

source/blog/2018-08-24-the-ember-times-issue-61.md
Adds a short write up on the Modifiers RFC and the almost finished intro this week's Readers' Question.
=> For EmberTimes#61: Add Modifiers RFC + Readers' Question

source/blog/2018-08-24-the-ember-times-issue-61.md
- Adds ember-truth-helpers section to the times
=> Adds ember-truth-helpers section to the times

source/blog/2018-08-24-the-ember-times-issue-61.md
Entry on https://twitter.com/samselikoff/status/1032298098901639169
=> blog(embertimes61): Podcast Melanie Sumner

source/blog/2018-08-24-the-ember-times-issue-61.md
=> Fixed some grammer, title + alias, links, hello

lib/versions.rb
=> Use the guides' versions file

source/blog/2018-08-31-the-ember-times-issue-62.md
[rendered](https://github.com/chrisrng/website/blob/55f91959af0845d9a8752d43828a7f278ea1e195/source/blog/2018-08-31-the-ember-times-issue-62.md)
=> blog(embertimes62): Ember 2018 Roadmap RFC

scripts/language-check.sh
```bash
The command "npm install alex --global" exited with 0.
0.01s$ bash scripts/language-check.sh
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
from e.g. this build: https://travis-ci.org/emberjs/website/builds/422899143
The remote, e.g. `origin/master` in our CI process is currently unknown for feature branch builds. To make sure we can diff a branch against the correct remote, this sets the remote accordingly, so builds can infer which changes have been checked in since their branch away from `master`:
=> Run Alex linter against the diff from the correct base branch (master)

source/blog/_sidebar.html.erb
This adds the Newsletter tag link under Browse by Subject
Adding here:
=> Adding Newsletter tag to Browse by Subject

source/blog/2018-09-07-the-ember-times-issue-63.md
=> For EmberTimes No. 63: blog(embertimes#63): add section on discord migration

source/blog/2018-09-07-the-ember-times-issue-63.md
Add A bigger tent blog post to the Times
=> Add A bigger tent blog post

source/blog/embertimes-template.md
This is repeated in every blog post on emberjs.com/blog. Put in Goodbits only? See #support-ember-times on Discord. cc @cah-danmonroe / @danmonroe
=> [Ember Times] Update embertimes-template.md

source/blog/2018-09-14-the-ember-times-issue-64.md
=> [Ember Times] Amy writeup for issue 64

source/blog/2018-09-14-the-ember-times-issue-64.md
Also fixed a runaway `)` in Discord section :)
=> Add section on State of JavaScript Survey 2018

source/blog/2018-09-21-the-ember-times-issue-65.md
@NullVoxPopuli let me know what you think!
=> [Ember Times] Add writeup on The EmberJS of the future... today!

source/blog/2018-09-21-the-ember-times-issue-65.md
short and sweet, lmk if any feedback!
=> Add writeup on ember-css-modules

source/blog/embertimes-template.md
Originally we removed this from the blog, and just put it in the Goodbits, based on reader feedback. 
What do you think about moving this to the "Want to write for the Ember Times?" section, since it's not necessarily a way to hook the reader? Then could be back in both(?) or just the Goodbits?
This is minutiae so just tagging you two for now since don't want to overload the Times team with PR's tonite. That being said, anyone's feedback is welcome!
=> [Ember Times] Update Ember Times template

source/blog/2018-09-21-the-ember-times-issue-65.md
slightly tweaked template
should add "add to intro" to instructions
=> [ember times] add intro

source/blog/2018-09-28-the-ember-times-issue-66.md
=> For Ember Times 66: Add Collocated Addon Test RFC Section

source/blog/2018-09-28-the-ember-times-issue-66.md
Not sure if this is applicable or not. :woman_shrugging: :man_shrugging:
=> Add entry for file structure blog post.

source/blog/2018-09-28-the-ember-times-issue-66.md
=> Fixed Header, Added Emoji, Added Hello :)

source/blog/embertimes-template.md
Relates to: https://github.com/emberjs/website/pull/3587
=> emojify template

source/about.html.erb
This updates the homepage title.
Issue #3521
=> Fixes the title of the homepage

source/blog/2018-10-05-the-ember-times-issue-67.md
Also added template addition from https://github.com/emberjs/website/pull/3599
=> [embertimes] Add Hacktoberfest writeup 🎃

source/blog/CONTRIBUTING.md
[rendered](https://github.com/emberjs/website/blob/181b14dfb29a8a4519ffd30e7a94f66b50ddafe2/source/blog/CONTRIBUTING.md#contributing)
=> docs(contributing): Move from Slack to Discord

source/blog/2018-10-05-the-ember-times-issue-67.md
[rendered](https://github.com/emberjs/website/blob/5c6baafe18df03726382ddfbd7d1ec9989b2341c/source/blog/2018-10-05-the-ember-times-issue-67.md#introducing-storybook-for-ember-)
=> blog(embertimes67): storybook for ember

source/blog/2018-10-05-the-ember-times-issue-67.md
=> Added section on CodeSandbox Ember

source/blog/2018-10-05-the-ember-times-issue-67.md
Also, 
- First stab at intro (I'm terrible at writing the intro, feel free to edit at will!)
- Copy edits
=> [embertimes]  Add update to Hacktoberfest writeup

source/blog/2018-10-05-the-ember-times-issue-67.md
=> Add link to community discord and bold a few things

source/blog/2018-08-27-ember-3-4-released.md
=> [WIP] For 3.4 Release Post: Add Ember CLI Release Notes

source/blog/2018-08-27-ember-3-4-released.md
=> For 3.4 Release Post: Update Ember CLI Release Notes

Gemfile.lock
See: https://nvd.nist.gov/vuln/detail/CVE-2018-1000201
Ran `bundle update ffi`
Co-authored-by: @tundal45
WAS:
IS: 
Error should go away on GitHub after merge
=> Update ffi to resolve security vulnerability

source/meetup-assets.html.erb
Updates contact instructions.
N/A
N/A
=> Copy update

source/blog/2018-10-07-ember-3-4-released.md
=> For 3.4 Release Post: Patch Releases

source/blog/2018-10-12-the-ember-times-issue-68.md
[rendered](https://github.com/emberjs/website/blob/0cbaa2e8164ed28cdb5a32fbe3d91aa805ddf071/source/blog/2018-10-12-the-ember-times-issue-68.md#quest-write-the-mvp-of-new-ember-cli-guides-)
=> blog(embertimes68): MVP of new ember-cli-guides

source/blog/2018-10-12-the-ember-times-issue-68.md
=> [#embertimes] Add writeup on ember-flatpickr

source/blog/2018-10-15-ember-3-5-released.md
=> Fix grammar in 3.5 Release Blog Post

source/layout.erb, source/manifest.json
Adds a Web App Manifest to the project.
Closes https://github.com/emberjs/website/issues/2965
=> Add Web App Manifest (fixes #2965)

source/blog/2018-11-19-ember-3-6-released.md
Adds the Native Class feature section to the blog post, along with related deprecations that were part of this work.
=> [3.6] Adds the Native Class release notes

source/blog/2018-11-09-the-ember-times-issue-72.md
=> For EmberTimes No. 72: Add Testing Help Wanted CTA

source/blog/2018-11-09-the-ember-times-issue-72.md
=> blog(embertimes72): copy changes

source/blog/2018-11-09-the-ember-times-issue-72.md
made minor tweaks to intro
other stuff was goodbits only
=> Copy updates from Goodbits

source/blog/2018-11-16-the-ember-times-issue-73.md
Adds teaser content regarding the DecEmber learning team event.
=> DecEmber announcement

source/blog/2018-11-16-the-ember-times-issue-73.md
=> Added some formatting, bolding, credit

source/blog/2018-11-16-the-ember-times-issue-73.md
=> fix(embertimes73): button too small for text

source/blog/2018-11-23-the-emberjs-times-issue-74.md
[rendered](https://github.com/emberjs/website/blob/0f3416b009e79b12f5b5b391c37991ddc180be8b/source/blog/2018-11-23-the-emberjs-times-issue-74.md#rfc-for-ember-data-packages-)
=> blog(embertimes74): emberdata packages

source/blog/2018-11-30-the-emberjs-times-issue-75.md
⬆️ Add sections on RFC RFC and Subreddit
=> [Ember Times] Add sections on RFC RFC and Subreddit

source/blog/2018-11-30-the-emberjs-times-issue-75.md
Writing on https://twitter.com/gavinjoyce/status/1068208916117577728
=> blog(embertimes75): painting game tutorial

source/blog/2018-11-23-the-emberjs-times-issue-74.md, source/blog/2018-11-30-the-emberjs-times-issue-75.md
> [...] you can go ahead and share in the Times. Please include a note that a full writeup is on the way soon
It would be lovely to have more people using this and adding content ASAP
Todos:
=> The Ember Times - Issue No. 75

source/blog/2018-12-07-the-ember-times-issue-76.md
[rendered](https://github.com/emberjs/website/blob/f2a10bb3b651081f88835a5f41b79c3d02928fde/source/blog/2018-12-07-the-ember-times-issue-76.md#tracked-properties-rfc-is-up-for-review-)
=> blog(embertimes76): tracked properties rfc

source/blog/2018-12-07-the-ember-times-issue-76.md
=> For EmberTimes No. 76: Add Contributors + December Writeup

source/blog/2018-11-30-the-emberjs-times-issue-75.md, source/blog/2018-12-07-the-ember-times-issue-76.md
=> The Ember Times - Issue No. 76

source/blog/2018-12-07-the-ember-times-issue-76.md
=> Fix double intro for npm survey

source/blog/2018-12-07-the-ember-times-issue-76.md
I am not sure why this made https://github.com/emberjs/website/pull/3722 fail, but not master
=> Add alex ignore to fix build

source/blog/2018-12-14-the-ember-times-issue-77.md
=> For EmberTimes No. 77: Add Boolean Arg Writeup

source/blog/2018-12-14-the-ember-times-issue-77.md
=> For EmberTimes No. 77: Contributors

source/blog/2018-12-17-mentorship-program.md
...though we should pass this back and forth again :p
=> Some edits

source/blog/2018-12-21-the-ember-times-issue-78.md
=> Add EmberConf reg writeup to issue

source/blog/2018-12-21-the-ember-times-issue-78.md
=> For EmberTimes No. 78: Add Mentorship Program Announcement

source/blog/2018-12-21-the-ember-times-issue-78.md
=> hotfix: ember times alex linting

.travis.yml
This upgrades bundler to > v2 as described in [the documentation update for Travis Ruby builds](https://docs.travis-ci.com/user/languages/ruby/#bundler-20).
=> Upgrade Bundler Version

source/blog/_sidebar.html.erb
https://emberjs.com/blog/tags/2019.html
=> Update sidebar to have 2019 tag for posts

source/blog/2019-01-18-the-ember-times-issue-81.md
=> For Ember Times No. 81: add interview link

source/blog/2019-01-18-the-ember-times-issue-81.md
[rendered](https://github.com/emberjs/website/blob/1f7233416defa1e6a053af01273121bf42f8d372/source/blog/2019-01-18-the-ember-times-issue-81.md#rfc-restructuring-the-guides-table-of-contents-)
=> blog(embertimes81): Restructuring Guides ToC

source/stylesheets/about.css.scss, source/stylesheets/base/_structure.scss
http://joxi.ru/zANM7VatB3e9g2
Remove container
add max-width to 991 because
http://joxi.ru/RmzBjkbt0E8Pkm
right arrow on the first screen
=> fix 768 display

source/blog/2019-01-26-emberjs-native-class-update-2019-edition.md
Cross posts the [Native Class Update: 2019 Edition](https://www.pzuraq.com/emberjs-native-class-update-2019-edition/).
cc @MelSumner 
N/A
N/A
=> [BLOG] Adds Native Class Update 2019 Edition

source/blog/2019-01-26-emberjs-native-class-update-2019-edition.md
I was informed this morning that one of the links in my post had been broken, this updates the link.
=> Update link address

source/blog/2019-02-01-the-ember-times-issue-83.md
[rendered](https://github.com/emberjs/website/blob/290c73bb051e808c76260b7736080db580e340db/source/blog/2019-02-01-the-ember-times-issue-83.md#rfcs-in-final-comment-period-%EF%B8%8F)
=> blog(embertimes83): FCP RFCs

source/blog/2019-02-01-the-ember-times-issue-83.md
@kennethlarsen is this writeup ok with you? it's def short and sweet
=> Ember Times: Native classes and This.JavaScript writeup 

source/blog/2019-02-01-the-ember-times-issue-83.md
=> fixed tiny typo

data/tomsters.yml
Fixes #3806, I forgot to commit the `yml` file in that PR :(
=> Add brazil tomster to yml

source/blog/2019-02-11-coming-soon-in-ember-octane-part-1.md
Cross posts the [Coming Soon in Ember Octane](https://www.pzuraq.com/coming-soon-in-ember-octane-part-1-native-classes/) blog post
=> Adds Coming Soon in Ember Octane Part 1

source/meetup-assets.html.erb
Removed the `-` that pretended to be bullet points. 
Updated the text with @wifelette's new text.
@MelSumner I wanted to use the `<dfn>` tag to be both visually and screen-reader accessible, but in the ember website `<dfn> is not styled italic. Do you know why?
***Before***
***After***
=> Update bullets and text in meetup-assets

source/blog/2019-02-18-ember-3-8-released.md
Write up of the `{{array}}` helper.
@kennethlarsen asked me to write it.
=> Write part on Array helper for 3.8 release blog

source/blog/2019-02-14-octane-guides.md
Publicly describe the documentation process for the Octane edition of Ember.
=> blog post to outline Octane documentation approach

source/blog/2019-02-19-coming-soon-in-ember-octane-part-2.md
Cross posts the second Coming Soon in Ember Octane blog post!
=>  Adds Coming Soon in Ember Octane Part 2

data/meetups.yml
Add Ember Madrid Meetup to the list.
https://www.meetup.com/es-ES/Ember-js-Madrid
https://www.emberjs.com/community/meetups/
=> Add Ember Madrid Meetup

data/meetups.yml
This updates the organiser list for the current Ember.js Berlin meetup.
=> upd(meetups): update organizer list for Ember Berlin meetup

source/blog/2019-02-22-the-ember-times-issue-86.md
Adds Ember Weekend RFC Roundup Redux content
=> Ember Weekend RFC Roundup Redux

source/blog/2019-02-26-coming-soon-in-ember-octane-part-3.md
Crossposts the 3rd post in the Coming Soon series!
=>  Adds Coming Soon in Ember Octane Part 3

source/blog/2019-03-01-the-ember-times-issue-87.md
Adds RFC 454 on Single File Components & Template Imports
=> RFC 454 on Single File Components & Template Imports

source/blog/2019-03-06-coming-soon-in-ember-octane-part-4.md
Crossposts the 4th post in the coming soon in Ember Octane series
=> [CROSSPOST] Coming soon in ember octane part 4

source/blog/2019-03-08-the-ember-times-issue-88.md
=> Add ember octane tech preview video

source/blog/2019-03-08-the-ember-times-issue-88.md
=> For EmberTimes No. 88: Add Anglebrackets RFC
